-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jan 30, 2025 at 08:17 AM
-- Server version: 8.0.41
-- PHP Version: 8.3.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `asucapstone_jmtlqnmy_capstone_project_submission`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin_pass_hash`
--

CREATE TABLE `admin_pass_hash` (
  `id` int NOT NULL,
  `pass_hash` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `admin_pass_hash`
--

INSERT INTO `admin_pass_hash` (`id`, `pass_hash`) VALUES
(1, '$2y$12$QyKl.ZuNbrE7e84b/eYWNezmytXRjftjO83CR62BBoHvwSF868LdS'),
(2, '$2y$12$QyKl.ZuNbrE7e84b/eYWNezmytXRjftjO83CR62BBoHvwSF868LdS');

-- --------------------------------------------------------

--
-- Table structure for table `ShowcaseEntries`
--

CREATE TABLE `ShowcaseEntries` (
  `EntryID` int NOT NULL,
  `Email` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `Name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `ProjectTitle` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `ProjectDescription` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `Sponsor` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `NumberOfMembers` int NOT NULL,
  `MemberNames` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `CourseNumber` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `Demo` enum('Yes','No') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `Power` enum('Yes','No') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `NDA` enum('Yes','No') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `VideoLink` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `VideoLinkRaw` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `DateStamp` date NOT NULL,
  `ShouldDisplay` enum('YES','NO') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dumping data for table `ShowcaseEntries`
--

INSERT INTO `ShowcaseEntries` (`EntryID`, `Email`, `Name`, `ProjectTitle`, `ProjectDescription`, `Sponsor`, `NumberOfMembers`, `MemberNames`, `CourseNumber`, `Demo`, `Power`, `NDA`, `VideoLink`, `VideoLinkRaw`, `DateStamp`, `ShouldDisplay`) VALUES
(1, 'ykim340@asu.edu', 'Yeonghyeon Kim', 'CS/E-070 School of Computing and Augmented Intelligence  - Interactive 3D Data Analytics Learning Environment', 'This project provides an interactive 3D environment to help students understand complex machine learning algorithms, such as binary classification and k-nearest neighbors, through interactive visualizations. Developed in Unity, the application allows users to choose datasets, select supervised and unsupervised learning algorithms, and view 3D-rendered results. The final product will be used in the project sponsor’s machine learning courses as an additional resource for students, enhancing comprehension of data analysis techniques.', 'Samira Ghayekhloo, samira.ghayekhloo@asu.edu', 5, 'Evelyn Brannen, Baylor Harrison, Jack Heckenlaible, Yeonghyeon Kim, Bradley Maggs', 'CSE486, CSE424', 'No', 'No', 'No', 'https://www.youtube.com/embed/cAOTGRZZ8Mo', 'https://youtu.be/cAOTGRZZ8Mo', '2024-11-17', 'YES'),
(2, 'jlateef@asu.edu', 'Junayd Lateef', 'CS/E-006 AOKMarketing.com - Chattable', 'Chattable is a marketing chatbot that answers any questions a person has about marketing. Chattable can recommend blog posts on the AOKMarketing website along with providing robust responses.', 'Mr. Dave Burnett (Founder of AOKMarketing.com)', 3, 'Junayd Lateef, Peter Vinci, Pavitra Guthy', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/2Ap6dz21gyk', 'https://youtu.be/2Ap6dz21gyk', '2024-11-19', 'YES'),
(3, 'mdmorten@asu.edu', 'Madison Mortensen', 'CS/E-089 Yanbor LLC - Develop testing system for the site OUReports.com', 'The testing system encompasses several key features: test case execution for critical components, validation of dropdown functionalities, navigation checks, and detailed logging for test results. By combining cutting-edge tools and methodologies, the Yanbor LLC Testing System has evolved into a reliable framework that significantly reduces manual effort, enhances test accuracy, and ensures system reliability.', 'Irina Yaroshevskaya', 2, 'Madison Mortensen, Jaston White', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/x3Y1aXdNe50', 'https://youtu.be/x3Y1aXdNe50', '2024-11-19', 'YES'),
(4, 'jiayuany@asu.edu', 'Jiayuan Yu', 'CS/E-015 Capstone Project Submission Group - ASU', 'The ASU Capstone Submission Project streamlines the submission process while enhancing the judging and showcase experience for capstone projects. It ensures secure data handling, dynamic project displays, and an intuitive user interface tailored for students, judges, and administrators.', 'Steven Osburn', 3, 'Ahmed Juvale, Jiayuan Yu, Tyler Shurley', 'CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/k5KXw8O_I74', 'https://youtu.be/k5KXw8O_I74', '2024-11-20', 'YES'),
(5, 'ttyagi1@asu.edu', 'Tushar Tyagi', 'CS/E-075 Shoptaki  - CEO', 'iOS App that utilizes AI to provide health advice and the provision of a follow-up chat based on a person’s health profile.', 'Asnee Fernando', 2, 'Gage Smith, Tushar Tyagi', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/PSN7KNmaG_c', 'https://www.youtube.com/watch?v=PSN7KNmaG_c', '2024-11-20', 'NO'),
(6, 'kghayal@asu.edu', 'Kaustubh Ghayal', 'IEE-004 Abbott: Equipment Changeover', 'Abbott Scottsdale manufactures electronic assemblies for use in implantable medical devices. This project follows a “DMAIC” process and aims to improve production by increasing equipment utilization on three solder lines by 10% through higher throughput and reduced downtime.', 'Hudson Whillock, Kim Hicks', 3, 'Kaustubh Ghayal, Parth Patel, Nikolas Cabrera', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/weNxLWo4y9M', 'https://www.youtube.com/watch?v=weNxLWo4y9M', '2024-11-21', 'YES'),
(7, 'jrpraini@asu.edu', 'Joseph Prainito', 'CS/E-036 InnC LLC - ArtVision Renderer', 'This application empowers users to explore and refine their unique art preferences. By interacting with the site’s features, users can curate a personalized art profile and generate bespoke artworks. These creations can be commissioned by an artist, transforming digital visions into real-life masterpieces.', 'Priyanka Khati', 5, 'Joseph Prainito, Emerson Carter, Bailey Learned, Cristian Roque, Thomas San Martin', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/DivG2THd3Gc', 'https://www.youtube.com/watch?v=DivG2THd3Gc', '2024-11-21', 'NO'),
(8, 'ahurowyj@asu.edu', 'Anna Hurowyj', 'IEE-005 L3Harris: Power Supply', 'The power supply cell manufacturing process has inefficiencies in workflow due to underutilized space and excess transportation distances. Our team produced a future state layout that is estimated to reduce inventory by 74%, reduce travel distance by 68%, and improve space utilization by 41%. The project is estimated to generate savings of $757,000 through the reduction in inventory.', 'Addie Smart and Adam Kuper', 2, 'Anna Hurowyj and Sean Nguyen', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/0_oCSmSddIo', 'https://www.youtube.com/watch?v=0_oCSmSddIo', '2024-11-21', 'YES'),
(9, 'akamdar2@asu.edu', 'Anay Kamdar', 'CS/E-066 Reality Articulated - Empath-iOS', 'The Empath app is an iOS application designed to enhance communication between therapists and their patients. It uses AI-powered sentiment analysis to transform journal entries into actionable insights, highlighting keywords, emotions, and recurring themes. By presenting this data through intuitive visualizations, the app saves therapy time and empowers therapists to provide targeted, effective care.', 'Karan Patil, Div Khare', 4, 'Srinath Amareni, saqib reza, noma gudur, Anay kamdar', 'CSE 424,CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/YZoSOZ5cZM4', 'https://youtu.be/YZoSOZ5cZM4', '2024-11-21', 'YES'),
(10, 'drquan@asu.edu', 'Daniel Quan', 'CS/E-060 Pathscape - Pathscape Mobile App Development', 'This team was tasked with laying the foundation for Pathscape\'s mobile application development; Building an application from the ground up in React Native for both Android and IOS.', 'Abiola Abraham', 4, 'Daniel Quan, Jack Curcio, Adam Douillet, Anish Nallani', 'CSE 486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/Shc3aCEM8xQ', 'https://youtu.be/Shc3aCEM8xQ', '2024-11-22', 'NO'),
(12, 'knavrati@asu.edu', 'Kyle Navratil', 'CS/E-026 Favoland - AI-driven beauty ingredient database and rating system', 'A beauty product rating website that utilizes AI to analyze and grade the safety of various beauty products.', 'Jeff Clark', 3, 'Kyle Navratil, Mark Fishman, Junichi Koizumi', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/eFdHSZfKK6c', 'https://www.youtube.com/watch?v=eFdHSZfKK6c', '2024-11-22', 'NO'),
(13, 'nalewis3@asu.edu', 'Nicklaus lewis', 'CS/E-061 Personal Project - Works for Northrop Grumman Corp - Digital Video Maipulation', 'This project focuses on developing a robust real-time object tracking system for live sports broadcasting, leveraging advanced machine learning and computer vision technologies. By transitioning from traditional OpenCV-based methods to Roboflow Inference and Supervision, the system achieves enhanced accuracy, seamless re-identification, and reliable tracking under dynamic conditions. The final implementation ensures low-latency performance, delivering a smooth and engaging experience for viewers while addressing the unique challenges of live sports coverage.', 'Eric Trant', 5, 'Nicklaus Lewis, Karem Gonzalez, Samuel Martin, Kai Reataza, Neel Madhav Dogra', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/4NiOMHVfxKA', 'https://youtu.be/4NiOMHVfxKA', '2024-11-22', 'NO'),
(15, 'svallu10@asu.edu', 'Sishir Vallurupalli', 'CS/E-072 School of Geog Science & Urban Planning, ASU - Automated Detection of Traffic and Street Environments', 'An early iteration of a generalized platform that aims to streamline object counting by making the process more programmatically friendly and collaborative. The platform allows users to upload footage, define counting boundaries, and efficiently manage many object categories through a click of a button. Serving as a prerequisite step toward fully automated object counting with plans to integrate tracking algorithms in a plug-and-play manner, in the interim, it enhances manual counting efficiency and lays the groundwork for future algorithm development.', 'Suhail Ghafoor, Hue-Tam Jamme', 4, 'Mitsuaki David Fukuzaki, Adit Prabhu, Sishir Vallurupalli, Jiandong Guan', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/3UNcslZIXXs', 'https://youtu.be/3UNcslZIXXs', '2024-11-22', 'YES'),
(16, 'mcjense3@asu.edu', 'Michael Jensen', 'CS/E-030 General Dynamics Mission Systems - Quantum Image Denoising using computational basis states', 'Creating an image denoiser that leverages the power of quantum computing.', 'Glen Uehara', 5, 'Danil Safikyurdskiy, Jacob Mattoka, Joshua Hutchinson, Michael Jensen, Michael Rejo', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/sne1dnkvnz0', 'https://youtu.be/sne1dnkvnz0', '2024-11-22', 'NO'),
(17, 'jjgreer@asu.edu', 'Joshua Greer', 'CS/E-045 Local Grow Salads - Grower', 'Local Grown Salads (LGS) is an indoor vertical farming technology company with a purpose to provide organic salads that are fresher, healthier, safer, and better tasting! Our project assignment was with the “Grower” team, whose goal is to collect, organize, analyze, and display data across every team in the LGS Ecosystem. Our assigned deliverables were: creating high level overview documentation (data flow diagrams), revising the team roadmap, and implementing the project management process. We also accepted additional responsibilities, such as: designing the Grower dashboard UX, integrating the database, and adding functionality documentation (previously skipped by other capstone teams).', 'Zale Tabakman', 3, 'Joshua Greer, Darsh Agarwal, Sathwik Reddy Mopuru', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/xyMOOgDWJXc', 'https://youtu.be/xyMOOgDWJXc', '2024-11-22', 'NO'),
(18, 'nrames22@asu.edu', 'Naveen Ramesh', 'CS/E-009 ASU Capstone Showcase', 'The ASU capstone showcase website is an online platform that was created to display Ira A. Fulton Schools of Engineering students\' capstone projects at the end of each semester. It includes a home page, navigation menu, pages for each major, admin dashboard, and a survey form for students to submit their project and other important information.', 'Steven Osburn (sdosburn@asu.edu)', 5, 'Waleed Briouig, Anush Garimella, Naveen Ramesh, Makenzie Rutledge, Ansh Tiwari', 'CSE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/mZ3l17XQ2qM', 'https://youtu.be/mZ3l17XQ2qM', '2024-11-22', 'YES'),
(19, 'jfurnia@asu.edu', 'James S Furnia', 'IEE-001 Goodyear 1: COI', 'The City of Goodyear has numerous contracts with many different vendors and seeks to reduce the time it takes to communicate with vendors ensuring the timely validation of all certificates. The team has been refining the City of Goodyear\'s certificate of insurance process using DMAIC methodologies, implementing software changes and data tracking. The team was able to achieve a 34% improvement in contract completion between the months of January and September.', 'City of Goodyear - Willy Elizondo, Tim Fisher', 3, 'James Furnia, Liya Samuel, Diego Flores', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/i3CRrBfWgj0', 'https://youtu.be/i3CRrBfWgj0', '2024-11-22', 'YES'),
(20, 'ndshumwa@asu.edu', 'Neil Shumway', 'IEE-003 Goodyear 3: Process Modeling', 'The City of Goodyear has experienced tremendous growth as the Metro Phoenix valley continues to expand. With this growth, stress has been put upon the company to find new ways to improve the work that they do without losing pace to the increased demand. The Continuous Process Manager has requested to be able to experiment with his idea to capture the current processes in a modeling software called Process Playground and generate data to indicate to his team where improvements can be made.', 'City of Goodyear/ Tim Fisher', 3, 'Neil Shumway, Giovanni Perez Orduno, Jim Chowdhury', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/th2afhkBiGA', 'https://www.youtube.com/watch?v=th2afhkBiGA', '2024-11-22', 'YES'),
(21, 'svers@asu.edu', 'Noah Vers', 'CS/E-076 Shoptaki - Smartchain next evolution of distributed network', 'Smartchain is a new product that aims to connect different organizations with interoperability, speed, and security being it\'s top priority. Additionally, a number of products can be integrated into Smartchain, such as an AI model that translates natural language into SQL or another database query. With these products, industries like healthcare, finance, or insurance and many more are able to communicate with one another in a fast and secure manner boosting efficiency and productivity.', 'Asnee Fernando', 4, 'Tyler Ornelas, Andrew Fritsch, Noah Vers, Aditya Sharma', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/Osjp0XiXoD8', 'https://youtu.be/Osjp0XiXoD8', '2024-11-22', 'NO'),
(22, 'kharioka@asu.edu', 'Kevin Harioka', 'CS/E-041 KnowQuest Inc. - Web or Native App UI/UX Development', 'Redesigning the KnowQuest website to improve the user interface and user experience. We then developed these prototype pages into JavaScript code to integrate with the website\'s front-end.', 'Rahi Tajzadeh', 5, 'Orion Choy, Kevin Harioka, Timothy Smith, Augustine Suter, Felix Wu', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/5EhmuoVpwPM', 'https://www.youtube.com/watch?v=5EhmuoVpwPM', '2024-11-22', 'NO'),
(23, 'ajknoll3@asu.edu', 'Andrew Knoll', 'CS/E-014 BizBridge.io - BizBridge: Building out an AI-Agentic Workflow to Sell Small Businesses!', 'Over our time during the capstone, we worked on two projects that focused on enhancing BizBridge\'s platform. First, we redesigned their landing page to create a modern, intuitive, and visually appealing user interface, aligning with their brand goals. Additionally, we developed an AI-powered form builder that allows users to upload documents, such as PDFs, which the AI analyzes to automatically generate customized forms for client use. Together, these efforts streamlined the platform\'s usability while introducing innovative tools to improve efficiency and functionality.', 'Randall Baron-Chong & Winston Edwards', 5, 'Andrew Knoll, Alejandro Torres, Ayden Asuncion, Michael Carpenter, & Piyussh Singhal', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/ni362WTqTDQ', 'https://youtu.be/ni362WTqTDQ', '2024-11-22', 'NO'),
(24, 'jtriley2@asu.edu', 'Jared Riley', 'CS/E-046 Local Grow Salads - Inspector', 'This project focuses on real-time data monitoring and Statistical Process Control (SPC) for vertical farming systems at Local Grown Salads. Using Kafka for data transfer, the system collects and analyzes sensor data, identifies out-of-range values, and sends alerts to the Barn Team for quick action. Future enhancements include connecting to SQL databases, integrating with dashboards, and standardizing message types for seamless data management.', 'Local Grown Salads', 1, 'Jared Riley', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/5hK7EQboGsE', 'https://youtu.be/5hK7EQboGsE', '2024-11-22', 'NO'),
(25, 'etquinon@asu.edu', 'Ethan Quinones', 'CS/E-038 IT Partner LLC.-Software Development - Licensing Recommendation Tool for Microsoft 365', 'Microsoft 365 licensing recommendation tool that analyzes user-selected services and recommends optimal plans based on features, pricing, and service compatibility', 'mym@itpartner365.com', 3, 'Ethan Quinones, Wentao Cao, Kunal Ashan', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/eHgFhLeEvBo&t', 'https://www.youtube.com/watch?v=eHgFhLeEvBo&t=10s&ab_channel=JayTso', '2024-11-22', 'YES'),
(26, 'fghafuri@asu.edu', 'Faris Ghafuri', 'CS/E-071 School of Computing and Augmented Intelligence  - Smart Sound-to-Speech Interpreter for Security and Notification Systems', 'The Smart Sound-to-Speech Interpreter for Security and Notification Systems converts device sounds like alarms and notifications into clear, spoken messages. This system is designed to enhance accessibility for individuals with disabilities, particularly those who are visually impaired, by providing meaningful, actionable alerts. It bridges the gap between sound-based communication and user understanding, making environments safer and more inclusive.', 'Samira Ghayekhloo', 3, 'Benjamin Cho, Sai Roshan, Faris Ghafuri', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/rA6GVz0bDCM', 'https://www.youtube.com/watch?v=rA6GVz0bDCM', '2024-11-22', 'YES'),
(27, 'dband@asu.edu', 'Devika Band', 'CS/E-086 VariableAI - VariableAI - Model Team', 'AI-powered personal chatbot that emulates your writing style', 'Mahesh Gali and  Vikash Suthapali', 5, 'Devika Band, Rohaan Kamaraj, Shivom Khare, Ian Schultz, Yash Sharma', 'CS/E-086', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/Ltgic_KnvzI', 'https://youtu.be/Ltgic_KnvzI', '2024-11-22', 'NO'),
(28, 'alambat@asu.edu', 'Ameya Lambat', 'CS/E-067 Rock Climbing Routemaking AI - Student Project', 'A user-friendly tool that processes uploaded images of climbing walls to detect and identify holds, helping climbers analyze routes and setups efficiently. Designed to enhance training and route planning for the climbing community.', 'Dr. Yu Zhang', 3, 'Ameya Lambat, Malavika Nair, Ethan Weiss', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/54EtcolbdSU', 'https://youtu.be/54EtcolbdSU', '2024-11-22', 'YES'),
(29, 'ecrich1@asu.edu', 'Ethan Rich', 'CS/E-055 Northrop Grumman - Finance Reporting Tool', 'The Northrop Grumman Finance Reporting Tool is a web application to assist managers at Northrop with keeping track of project spending. Using a containerized full-stack application, this solution allows managers to upload raw time tracking data, view entries in the database, and graph spending over time for both employees and projects.', 'Tricia Dove', 2, 'Ethan Rich, Rahul Singh', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/wzKYBAyMUE4', 'https://www.youtube.com/watch?v=wzKYBAyMUE4', '2024-11-22', 'YES'),
(30, 'jmriffle@asu.edu', 'Juliana Riffle', 'CS/E-065 Reality Articulated - Empath-Dashboard', 'This project is an application that will be used in therapy to improve the therapist-client relationship by collecting, processing, and visualizing client data to provide useful insights that hopefully lead to more personalized and data-driven care.', 'Karan Patil', 3, 'Juliana Riffle, Hriday Niketu Shah, Mehul Kumar Srivastava', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/mjG3J_G6JB4', 'https://www.youtube.com/watch?v=mjG3J_G6JB4', '2024-11-22', 'YES'),
(31, 'jehosier@asu.edu', 'Jack Hosier', 'CS/E-049 Lotus - Addiction Therapy Inc -web /mobile development', 'Lotus Addiction Therapy LLC is an online platform that provides counseling services to help clients address addiction-related challenges.', 'Hamsharan Mahalingam', 3, 'Jack Hosier, Zachary Lee, Nupur Patel', 'CSE486, CSE486, CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/7s3tP9TptXU', 'https://youtu.be/7s3tP9TptXU', '2024-11-22', 'YES'),
(32, 'bashkena@asu.edu', 'Ben Ashkenazi', 'CS/E-062 Points Africa - Points Africa Mobile App Development', 'Points Africa is a mobile app that would allow users to earn points for everyday purchases (mobile payments, gas, grocery, pharmacy, and other retail activities) and spend them to pay for other goods and services that are offered by the businesses registered in the app’s retail network.', 'Strive Mazunga', 5, 'Kruthi Tirunagari, Ben Ashkenazi, Andre Kee, Deandra Prasetya Perdana, Aztlan Olmedo', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/W9a-vshTWCQ', 'https://youtu.be/W9a-vshTWCQ', '2024-11-22', 'NO'),
(33, 'ankamasa@asu.edu', 'Anuj Kamasamudram', 'CS/E-077 Shoptaki - Smartid universal identity', 'Develop a universal identity application to hod all your information. This can be easily accessed for users to keep securely and know where it is for the future.', 'Asnee Fernando', 2, 'Isaac Walker, Anuj Kamasamudram', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/Uv_ip3BMGNg', 'https://youtu.be/Uv_ip3BMGNg', '2024-11-22', 'NO'),
(34, 'bgriley1@asu.edu', 'Brenden Riley', 'CS/E-031 GLOBAL SENSOR SYSTEMS INC - Trade Show Display', 'Global Sensor Systems Inc. has asked us to develop a model car than can demonstrate their automatic reverse braking technology at a small scale. We accomplished this by using an ultrasonic sensor and Arduino logic.', 'Global Sensor Systems', 2, 'Anthony Touma, Brenden Riley', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/gArHMBLOX5I', 'https://youtu.be/gArHMBLOX5I', '2024-11-22', 'YES'),
(35, 'jwgood@asu.edu', 'Jacob Good', 'CS/E-034 Honeywell International - Build a block chain-based solution for UAM Data management.', 'This project aims to streamline Urban Air Mobility (UAM) data management through a blockchain-based solution, leveraging distributed ledger technology, to enhance data integrity, security, and transparency including a single source of truth. We will focus on developing a blockchain based system tailored for managing data related to UAM, including flight data, maintenance records, and passenger information. The scope encompasses the design, development, testing, and deployment of the blockchain solution, with a keen emphasis on scalability.', 'Rao, Nayyar', 5, 'Vansh Saxena, Binh Nguyen, Richard Matejka, Shreyash Singh, Jacob Good', 'CSE 486, 424', 'No', 'No', 'No', 'https://www.youtube.com/embed/lINQgnx7LxI', 'https://youtu.be/lINQgnx7LxI', '2024-11-23', 'YES'),
(36, 'agupt344@asu.edu', 'Atharva Gupta', 'CS/E-054 Naralytics - NLP & Classification Model Optimization', 'To Improve the performance of underlying machine learning models used to predict and classify emotions, perspectives, and personality traits.', 'Gyou Re Lee', 3, 'Amal Shaik, Atharva Gupta, Ziyue Qiu', 'CSE 486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/pk2WtK8tfK4', 'https://youtu.be/pk2WtK8tfK4', '2024-11-23', 'NO'),
(37, 'asaboonc@asu.edu', 'Aria Saboonchi Lilabady', 'CS/E-043 Local Grow Salads - Assembly', 'Local Grown Salad Assembly team was responsible for all the equipment on the farms and company.', 'Zale Tabakman', 2, 'Aria Saboonchi Lilabady, Chinmaya Bidkar', 'CSE 486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/TKeO8J-EIjk', 'https://youtu.be/TKeO8J-EIjk', '2024-11-23', 'NO'),
(38, 'aclacour@asu.edu', 'Annalise LaCourse', 'CS/E-064 QuestStone LLC. - Slack App + Microsoft Teams App Development', 'A Slack Task App which can be used within slack for teams/small businesses to manage their tasks.  The features a kanban board style grouping for tasks to mark their progress.  Tasks can also be monitored by multiple team members at the same time.', 'Christian Womack', 4, 'Gage Cates, Hunter Smith, Annalise LaCourse, Veda Valiveti', 'CSE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/yj2A1Ms7YPU', 'https://youtu.be/yj2A1Ms7YPU', '2024-11-23', 'YES'),
(39, 'rdrawson@asu.edu', 'Riley Rawson', 'CS/E-047 Local Grown Salads - LGS EcoSystem - Network', 'We developed a Network Dashboard for Local Grown Salads that facilitates the login and management of alerts. The application was built primarily using Typescript and various Javascript libraries. Our component is designed to work with other LGS systems seamlessly.', 'Zale Tabakman, zale@localgrownsalads.com', 3, 'Riley Rawson, Carlos Beltran Quinonez, Rakan Alotaibi', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/yjQrRm1c-nE', 'https://youtu.be/yjQrRm1c-nE', '2024-11-23', 'NO'),
(40, 'arkolan@asu.edu', 'Anish Kolan', 'CS/E-039 Jo Clark, CEO - Circle.ooo AI Initiative', 'This project seeks to add generative AI functionality to Circle.ooo through a virtual assistant to streamline event planning, and for AI generated event images from user-provided descriptions.', 'Jo Clark', 5, 'Kavinkumaar Jaganathan, Sejal Jain, Anish Kolan, Matthew Luo, Khushi Patel', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/TJ7_pWIz-Xk', 'https://youtu.be/TJ7_pWIz-Xk', '2024-11-23', 'NO'),
(41, 'zrundstr@asu.edu', 'Zachary Rundstrom', 'CS/E-040 Judy.ai - Judy.ai for Healthcare', 'The capstone project for Judy AI improved the user experience and functionality of the platform in the healthcare space. We redesigned its interface for easier navigation, integrated the Fullscript API for seamless purchasing of supplements, and added a feature for a donation gateway and Google API for the most accurate information regarding birthing location. These changes make Judy AI more accessible, informative, and user-friendly to support users\' needs in finding health resources and giving to health-related causes.', 'Eean -  eean@judefly.com', 2, ':Zachary Rundstrom, Armando Gonzalez', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/8QnOMAZXxpQ', 'https://youtu.be/8QnOMAZXxpQ', '2024-11-23', 'YES'),
(42, 'dnguye92@asu.edu', 'David Nguyen', 'CS/E-021 DigiClips  - DEBUG OPTION EMAIL ALERTS FRONT END SEARCH ENGINE TESTING', 'DigiClips is a media search engine that generates reports for various media sources including television, cable networks, social media, blogs, magazines, and newspapers. The search engine aims to help customers become increasingly media aware and informed by using a user friendly platform and media analytics.', 'Bob Shapiro, Henry Bremers', 3, 'Mariam Ayesh, Caleb Blackmon, David Nguyen, Aishwary Sharma', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/1r05mN399jE', 'https://youtu.be/1r05mN399jE', '2024-11-23', 'YES'),
(43, 'rferna33@asu.edu', 'Ryan Fernandes', 'CS/E-002 ABC Academy of Music - CLIENT SELF-MANAGEMENT • Hinna: Small Business Management Software', 'This project integrates a WordPress site into a Java-based backend, enabling seamless user authentication, secure API communication, and dynamic content management. It involves developing various microservices to handle user profiles, WordPress plugin integration, and system settings, while ensuring backup, security, and notification services are in place. The goal is to create a robust and scalable infrastructure that allows businesses to manage and monitor their WordPress installation within a larger platform.', 'Barnaby Kerekes', 3, 'Ryan Fernandes, Noah DeHaven, Oscar Ortiz', 'CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/LJ0ujc37Kzg', 'https://youtu.be/LJ0ujc37Kzg', '2024-11-23', 'YES'),
(44, 'ckroeper@asu.edu', 'Colin Kroeper', 'CS/E-027 Fourcher Technologies - Tracking bees using AI', 'Tracking bees using AI', 'Jordan Fourcher (jordanfourcher@fourchertech.com)', 5, 'Colin Kroeper, Zion Esemonu, Kyle Gavin, Abhinav Sharma, John Fitzpatrick', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/jkjIjkJLV8w', 'https://youtu.be/jkjIjkJLV8w', '2024-11-23', 'YES'),
(45, 'djimen38@asu.edu', 'Daniel Jimenez', 'IEE-009 ASU Earth and Space: Exhibit Planning', 'Cassie Bowman with the ASU Earth and Space department has requested services to design and develop pre-curated exhibit kits (themed after the NASA Psyche Mission) that museums and libraries can request for use in their venues. An implementation plan is to be created for this objective. This team has taken it upon themselves to assist in this goal.', 'NASA Psyche Program- Cassie Bowman', 3, 'Daniel Jimenez, Juan Pablo Gongora, Jaiden Coleman', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/aKK1Hx6kuNU', 'https://youtu.be/aKK1Hx6kuNU', '2024-11-23', 'YES'),
(46, 'skallred@asu.edu', 'Spencer Allred', 'CS/E-087 Velocified - Lean Enterprise LMS & Tracking Platform', 'Velocified LMS is designed to be a lean enterprise learning management system that enables organizations to create customizable Velocified Paths: progressive, calendar-based training sequences composed of Learning Activities. The platform features a minimalist interface where employees can progress through their assigned Velocified Paths while managers track completion and verify required compliance training.', 'Velocified', 2, 'Spencer Allred, Gabriel Ortega', 'CSE424,CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/7Y4Avz4z8sA', 'https://www.youtube.com/watch?v=7Y4Avz4z8sA', '2024-11-23', 'YES'),
(47, 'lmoro@asu.edu', 'Leo Moro', 'IEE-008 ASU Earth and Space: Social Media', 'ASU NASA\'s Psyche Team is seeking to improve their online presence and boost their crowd following. Our team researched and developed engagement plans for the five social media platforms that Psyche\'s Management team currently maintains!', 'NASA Psyche Mission', 3, 'Leo Moro, Matthew Warren, Natalie Cao', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/wri_4SMEsTs', 'https://youtu.be/wri_4SMEsTs', '2024-11-23', 'YES'),
(48, 'yasawant@asu.edu', 'Yash Sawant', 'CS/E-056 Nowhere Collective - A Circular Marketplace for Upcycling Makers and Conscious Consumers', 'The Nowhere Collective Circular Marketplace is a web application designed to promote sustainability by connecting makers and collectors through a circular economy model. It features AI-assisted listing creation, peer-to-peer material exchange, and automated email notifications for seamless interactions. The platform simplifies workflows and encourages active participation to reduce waste and foster collaboration.', 'Katy Osborn: katy@nowhere-collective.com', 2, 'Yash Sawant, Mariela Medina', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/2V5kXi3odqU', 'https://www.youtube.com/watch?v=2V5kXi3odqU', '2024-11-23', 'YES'),
(49, 'dmcquitt@asu.edu', 'Drake McQuitty', 'CS/E-083 VariableAI - VariableAI - Data Team', 'The VariableAI project focuses on developing a generative AI that mimics an individual’s unique writing style. By analyzing and learning from user-provided text, the AI enables users to streamline tasks like drafting emails or repetitive writing. This innovative tool can help boost productivity and cut down time spent on tedious writing tasks.', 'Mahesh Gali, Vikash Suthapalli', 5, 'Sergio Anzaldo Cortez, Maria Garcia, Zakary Kienitz, Drake McQuitty, Cong Wei', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/OjV2acpXCgE', 'https://youtu.be/OjV2acpXCgE', '2024-11-23', 'NO'),
(50, 'ochapele@asu.edu', 'Oghenerukevwe Chapele', 'CS/E-078 StayWell - StayWell Medical Habit Tracker Mobile App', 'StayWell is a mobile application aimed to help users better manage their personal health. The app acts as a habit tracker, appointment manager, and document storage. This would allow users to access all their health information from one convenient location.', 'Zoey Grant', 5, 'Oghenerukevwe Chapele, Danielle Ellis, Yu-Ling Lo,  Max Schumacher, Kyndra Wynne', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/1RG_rmibxpo', 'https://www.youtube.com/watch?v=1RG_rmibxpo', '2024-11-23', 'YES'),
(51, 'slowe8@asu.edu', 'Sean Lowe', 'CS/E-007 Arizona State University - Quantum Computing Tool for Education', 'The goal of this project is to implement a .NET quantum computing library to be implemented into ASU’s VIPLE application. Using the library through VIPLE, students of any discipline can learn about how quantum circuits work and explore the concepts of quantum computing in an interactive manner. By lowering the bar of entry into quantum computing, ASU can innovate in the field at a greater velocity.', 'Genaro De Luca, Yinong Chen', 5, 'Sean Lowe, Jett Bauman, Zachary Litwin, Griffith Simmon, Ryan Rajesh', 'CSE424, CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/5LsK2ES67nE', 'https://youtu.be/5LsK2ES67nE', '2024-11-23', 'YES'),
(52, 'ksingh54@asu.edu', 'kaushiki singh', 'CS/E-033 Honeywell International - Adaptive Announcement System', 'Our system will utilize either a .mp4 video file or live video. Based on the video, it will determine the average emotional sentiment of the initial ten frames of the video source. The system will then use the emotional sentiment to alter a sentence input by the user based on the emotional sentiment of the video.', 'Nichola Lubold', 5, 'James Ross, Kaushiki Singh, Jayashree Adivarahan, Jacob Buckingham, Olivia Huang', 'CSE 486, CSE 424', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/VYEw7L8SLGg', 'https://youtu.be/VYEw7L8SLGg', '2024-11-23', 'YES'),
(53, 'djain30@asu.edu', 'Dhruv Jain', 'CS/E-004 Alcove Ridge Consulting LLC - Unique experience to work on a cutting edge Fintech platform', 'Website and mobile app for a fintech platform facilitating private off-market deals, financial news updates, and nearby finance-related events or conferences.', 'Josh Smilowitz', 4, 'Dhruv Jain, Yash Raj Thakur, Bhanu Mayank Jha, Daniel Aguirella', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/vRMfZPgEAcc', 'https://youtu.be/vRMfZPgEAcc', '2024-11-23', 'NO'),
(54, 'asbabbit@asu.edu', 'Alma Babbit', 'CS/E-011 ASU SCAI - Web-Based RISC V Architecture Emulator in VIPLE Environment', 'This project aims to create an educational tool that uses the open-source RISC-V architecture to simplify the learning of computer architecture concepts. By integrating ASU’s visual programming environment VIPLE with the RISC-V simulator emulsiV, we intend to provide a hands-on experience to make difficult concepts easier to understand. Our goal is to ease the learning curve and increase engagement, making the study of computer architecture more accessible for students.', 'Yinong Chen and Gennaro de Luca', 3, 'Alma Babbit, John Cowan, Omar Olivas', 'CSE 424, CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/Z1IlQChRJnE', 'https://youtu.be/Z1IlQChRJnE', '2024-11-23', 'YES'),
(55, 'cmspenc8@asu.edu', 'Casey Spencer', 'CS/E-082 Toyz Electronics - Game Developer for Online Learning Platform', 'We developed an interactive, game-based online learning platform in collaboration with Toyz Electronics to engage students in STEAM (Science, Technology, Engineering, Arts, and Mathematics) education. Our platform offers multilingual support—including right-to-left and CJK languages—and data-driven insights using PlayFab. By enhancing user engagement with intuitive design and localization, we aim to connect students worldwide with potential STEAM career paths.', 'Damola Idowu', 4, 'Carson Cady, Majd Salti, Shray Soorma, Casey Spencer', 'CSE424, CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/SFaBGPbAT8k', 'https://www.youtube.com/watch?v=SFaBGPbAT8k', '2024-11-23', 'YES'),
(56, 'watkin@asu.edu', 'William Atkin', 'CS/E-024 DigiClips - Media Search Engine - Team 2', 'The DigiClips Media Search Engine is a web application that searches, organizes, and ships media mentions for interested clients. Our project was to create an Error Messaging System for the application, a software component that takes error messages generated by the user-facing application and sends them to a database for review and resolution.', 'Robert Shapiro', 4, 'Seoyeong Oh,  Almaha Alkhalouf, William Atkin, Luke Fasciano', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/ebhqcShK6Sk', 'https://www.youtube.com/watch?v=ebhqcShK6Sk', '2024-11-23', 'YES'),
(57, 'eblackst@asu.edu', 'Euan Blackstone', 'CS/E-019 Coconut CubeSat Software - Student Project', 'Coconut CubeSat is a 1u CubeSat dedicated to store and forwarding data from small ground nodes around the world.', 'Joe DuBois', 3, 'Euan Blackstone, Dylan Larson, Mitchell Zakocs', 'CSE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/yZa4130Q06c', 'https://youtu.be/yZa4130Q06c', '2024-11-23', 'YES'),
(58, 'jlusenho@asu.edu', 'Jacob Lusenhop', 'CS/E-063 Prescott Electric Motors - Electric Motor Monitoring System', 'The goal of this project is to create an product to collect, store, and view realtime data from an electric motor in an easy-to-use app.', 'Maxime Pilon', 7, 'Jacob Lusenhop, Karl Miranda, Hisham Ali Abdul Jaleel, Pooja Nara, Sabah Ashfeen, Nont Kaewtrakulpong, Diana Alonso', 'CSE424', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/d2yFAxBCypo', 'https://youtu.be/d2yFAxBCypo', '2024-11-23', 'NO'),
(59, 'yrai2@asu.edu', 'Yashasvi Rai', 'CS/E-032 Hawkeye Early Detection System - Hawkeye Early Detection System', 'We developed a web application designed to enhance school safety with real time threat detection. It leverages advanced technologies to provide secure and user friendly solution for administrators using the website. The system when completely integrated will display proactive threat management.', 'Juliet Sonnenberg', 5, 'Yashasvi Rai, Yash Sarkar, Dhruv Jain, Gabriel Bhardwaj, Parth Bhangale', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/h5IP_Bsn4rY', 'https://youtu.be/h5IP_Bsn4rY', '2024-11-23', 'YES'),
(60, 'kdsnyde4@asu.edu', 'Katherine Snyder', 'IEE-011 Amkor Material Cost Estimator', 'This project provides a calculator capable of estimating the price of materials used in semiconductor fabs. The calculator uses regression formulas of similar previously purchased materials, based on attributes inputted by the user, to give an estimated should-be cost of materials. The final product will be used by the project sponsor team to provide a base price for negotiation and reduce time spent reviewing previous sales data for similar items.', 'Amkor', 1, 'Katherine Snyder', 'IEE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/6Pg3K_u_0vA?si=dIV8wa0_nUDFiKkm', 'https://youtu.be/6Pg3K_u_0vA?si=dIV8wa0_nUDFiKkm', '2024-11-23', 'NO'),
(61, 'ialemu@asu.edu', 'Isaac Alemu', 'CS/E-016 Capstone Project Ticketing System', 'The ticketing system allows students to report issues related to their capstone projects, such as sponsor concerns and team challenges, through an easy-to-use web application. Instructors can then review, respond to, and manage these tickets, enabling streamlined communication and timely resolution of student concerns.', 'Steven Osburn', 5, 'Rhea Mane, Ryan Radtke, Isaac Alemu, Kevin Tang, Shabib Huq', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/JbsiEPwoCdw', 'https://www.youtube.com/watch?v=JbsiEPwoCdw', '2024-11-23', 'YES'),
(62, 'askorn@asu.edu', 'Alexander Korn', 'CS/E-050 Lotus Addiction Therapy Inc - Lotus', 'We have implemented a new subscription system for the Lotus Addiction Therapy website. This includes redesigning web pages and their layouts, creating new identifiers and systems in the backend framework, security features and more.', 'Hamsharan Mahalingham', 3, 'Alexander Korn, Zakery Cumbie, Mohammed Al Sharyan', 'CSE486, CSE424', 'No', 'No', 'No', 'https://www.youtube.com/embed/v4vRTC9D9Io', 'https://youtu.be/v4vRTC9D9Io', '2024-11-23', 'YES'),
(63, 'mhharper@asu.edu', 'Michael Harper', 'CS/E-079 Table Ready - AI-enhanced social media post generator and Infra Red seating detection system', 'Website for generating social media posts easily with either key words or an article url via ChatGPT and posting directly to Facebook and Instagram for small restaurants.', 'Juliet Sonnenberg', 3, 'Michael Harper, Huanran Yu, Amogh Rajendra', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/1ZTPVZ1Jbyg', 'https://youtu.be/1ZTPVZ1Jbyg', '2024-11-23', 'YES'),
(64, 'vtdang2@asu.edu', 'Vincent Dang', 'CS/E-020 Contak - Kinda Famous: Music Adventure Role Playing Video Game', 'An immersive open world RPG based on the city Phoenix. It’ll allow players of all walks of life to be able to create music in the form of combat, which will allow them to explore and conquer the entertainment scene of KindaFamous.', 'Tadi Prim', 3, 'Vincent Dang, Nathan CorwinShah, Shelbie Pyeatt', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/dTtqwle4CTo', 'https://youtu.be/dTtqwle4CTo', '2024-11-23', 'NO'),
(65, 'dcasti44@asu.edu', 'Dylan Castillo', 'CS/E-001 ABC Academy of Music - ABC Academy of Music • Custom Business Management Software', 'A Custom Business Management software that caters to service based businesses such as music schools.', 'Barnaby Kerekes', 3, 'Abdullah Al-Ani, Dylan Castillo, Kendrick White', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/5l-jHTHLa_w', 'https://youtu.be/5l-jHTHLa_w', '2024-11-23', 'NO'),
(66, 'dnewlin@asu.edu', 'Drew Newlin', 'IEE-006 ASU Athletics 1: Readiness Score', 'Our team took over a previous capstone groups\' project which was a program designed to graph force plate data from an ASU athletics team. The program previously made was mostly unusable and very difficult to maneuver around and had some issues with formulas and graphs. To fix these issues our team moved the program to a new software that is much more accessible and easier to use for the coach and we also added more metrics for coach Alosi to view, as well as corrected and added new formulas that we decided were necessary.', 'Peter Alosi', 3, 'Drew Newlin, Cameron Pazul, Clayton Kurtz', 'IEE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/LcvuKGRt7DQ', 'https://youtu.be/LcvuKGRt7DQ', '2024-11-23', 'YES'),
(67, 'lhuan137@asu.edu', 'Ling Chen, Huang', 'CS/E-008 ASU - Smart Knowledge Navigation and Discovery Platform', 'Schonograph is a tool that helps researchers easily search, save, and organize academic articles. It features search filters, bookmarking, and search history tracking. The platform is designed to make finding and managing research faster and simpler.', 'John M. Anderies', 3, 'Atharva Warke, Omar Hernandez, Ling-Chen Huang', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/fT7LvFMRtag', 'https://youtu.be/fT7LvFMRtag', '2024-11-23', 'YES'),
(68, 'pculley1@asu.edu', 'Peter Culley', 'IEE-007 ASU Athletics 2: Data Analysis', 'This project analyzed the relationship between force plate metrics and on-field performance for ASU Women’s Softball. By integrating neuromuscular metrics from countermovement jumps with hitting and pitching statistics, we identified key predictors of player performance. The findings aim to provide data-driven insights for optimizing training programs and improving athletic outcomes.', 'Peter Alosi (ASU Athletics)', 3, 'Peter Culley, Jake Hohu, Ahmed Khayat', 'IEE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/eIgt3e70Yfg', 'https://www.youtube.com/watch?v=eIgt3e70Yfg', '2024-11-23', 'YES'),
(69, 'ltprice@asu.edu', 'Lincoln Price', 'CS/E-074 Sense Science Lab LTD - Human AI Collaborative Drawing Tool Development', 'Sense Science Lab has created the MagicPen application, a program that generates single stroke drawings and utilizes the motor functionality of the MagicPen to guide the user\'s hand and pen along the stroke using haptic feedback that responds dynamically to the user\'s force.', 'Soheil Kianzad', 4, 'Lincoln Price, Austin Bingham, Nathan Le, Ryan Dagnino', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/OlGsbqftf1w', 'https://youtu.be/OlGsbqftf1w', '2024-11-23', 'NO'),
(70, 'serramil@asu.edu', 'Srivatsav Erramilli', 'CS/E-058 Omega Pediatrics - Mobile Messaging App for Doctors - AWS/ReactNative/DynamoDB', 'Our capstone project involved the development of a mobile application that enables patients to subscribe and engage in conversations with medical professionals.', 'Dr.Michael Nwaneri, MD', 5, 'Srivatsav Erramilli, Sandeep Reddy Bimidi, Aaron Ortiz, Sumukh Komati, Jeffrey Sellers', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/cmvOavcpLIg', 'https://youtu.be/cmvOavcpLIg', '2024-11-23', 'NO'),
(71, 'kkaterga@asu.edu', 'Kosta Katergaris', 'CS/E-013 Bit Space Development', 'A computer vision segmentation model for identifying minerals in unlabeled mineral slide images. Using state-of-the-art techniques like self-supervised learning and unsupervised techniques, specifically a fine-tuned DINO backbone and MaskCut, the model processes large images divided into overlapping patches to capture fine-grained details.', 'Bit Space Development: Daniel Blair & Jameel deBeer', 5, 'Konstantinos Katergaris, Alex Myers, Jordan Wong, Aaron Johnson, ChaitanyaKrishna Yaramachu', 'CSE 486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/rURpVvbNkco', 'https://www.youtube.com/watch?v=rURpVvbNkco', '2024-11-23', 'NO'),
(72, 'adnguy24@asu.edu', 'Andy Nguyen', 'CS/E-029 General Dynamics Mission Systems - Prototyping alternate GIS solutions for real-time scenarios', 'Research alternative GIS solutions in order to create at least 2 prototypes. Both prototypes were developed with Javascript, python, and the Leaflet or ArcGIS.', 'Selik Samai', 4, 'Carlos Corral-Williams, Andy Nguyen, Cory Tertel, James Zanetti', 'CSE 486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/EncVe4yKaxw', 'https://youtu.be/EncVe4yKaxw', '2024-11-23', 'NO'),
(73, 'bgaekwad@asu.edu', 'Brandon Gaekwad', 'IEE-002 Goodyear 2: TraCtion', 'The City of Goodyear, recognized for its forward-thinking approach to city management and continuous improvement, sponsored this project to address inefficiencies in project management processes. The initiative focused on implementing Moresteam’s TraCtion and Engineroom software to streamline reporting, improve data accuracy, and support leadership decision-making. By creating a user-friendly system, the project aimed to enable lean improvements, enhance efficiency, and ensure transparency in reporting to stakeholders, including the city council.', 'Tim Fisher', 3, 'Brandon Gaekwad, Basil Alibrahim, Easton Kiosterud', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/j1sSUFVLKfQ', 'https://youtu.be/j1sSUFVLKfQ', '2024-11-23', 'YES'),
(74, 'sgupt268@asu.edu', 'Sarva Gupta', 'CS/E-012 BetterEDU - BetterEDU', 'BetterEDU is based on a startup iOS and Android application to help college students with mental health through peer-led groups. We worked on creating a web application version of the mobile application to expand convenience and accessibility, while maintaining the style and structure of the mobile app.', 'Heather Cochran', 3, 'Sarva Gupta, Nisha Kulkarni, Jesse Jimenez', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/QvPCv6blu9Q', 'https://youtu.be/QvPCv6blu9Q', '2024-11-23', 'NO'),
(75, 'jcmcent1@asu.edu', 'Jesse McEntire', 'CS/E-010 ASU ECEE - Logic Tutor for the Web Phase 2', 'Logic Tutor Web (LTW) is the next iteration of Logic Tutor, an app that helps and teaches students the basics of the CSE/EEE 120 curriculum. LTW inherits all of the games and features from Logic Tutor and improves on the user experience for easier setup, access, and submission.', 'Steve Millman', 4, 'Lojain Algarni, Jincheng Chen,  Jesse Mcentire, Alvin Wang', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/sTyFORIY5vc', 'https://www.youtube.com/watch?v=sTyFORIY5vc', '2024-11-23', 'NO'),
(76, 'tpschafe@asu.edu', 'Thomas Schafer', 'CS/E-003 Ada Analytics - Website Development', 'Ada Analytics tasked the team with creating software that would improve the Ada product. The team therefore created a feedback/survey website and system that could increase user trust in the Ada product.', 'Dr. Ray Hsu', 3, 'Thomas Schafer, Harsh Vikram Singh, Janie Valenzuela', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/tnP431ZPvXE', 'https://youtu.be/tnP431ZPvXE', '2024-11-23', 'NO'),
(77, 'mpolacc1@asu.edu', 'Madison Polacca', 'CS/E-081 The Clean Divorce - Use technology to simplify & modernize divorce to support families', 'Our project focused on creating a Flutterflow app called CoPilot Kids, designed to support co-parenting by fostering stability and responsibility through positive reinforcement and goal-setting. CoPilot Kids reimagines chores with a gamified approach to boost motivation while also promoting emotional well-being through daily check-ins that acknowledge and validate children\'s feelings.', 'The Clean Divorce- Suzanne Winlove-Smith', 4, 'Madison Polacca, Changqiu Yin, Faisal Alhussain, Vedansh Arun Sharma', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/p0vElrmBhfM', 'https://youtu.be/p0vElrmBhfM', '2024-11-23', 'YES'),
(78, 'nlambias@asu.edu', 'Nicholas Lambiase', 'CS/E-084 VariableAI - VariableAI - Full Stack Team', 'VariableAI is a cloud-based platform that enables users to securely upload and analyze documents while interacting with a proprietary language model for personalized text. Built on a scalable microservices architecture using AWS, the system integrates user authentication, document management, and custom LLM responses to deliver a seamless, intelligent user experience.', 'Vikash Suthapalli, Mahesh Gali', 3, 'Nicholas Lambiase, Keegan Collier, Vivek Indlebele Narasimha Prasad', 'CSE486, CSE424', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/LlMgK5fFGCI', 'https://youtu.be/LlMgK5fFGCI', '2024-11-23', 'NO'),
(79, 'bswiech@asu.edu', 'Bartosz Swiech', 'CS/E-080 Tech Diversified - MARS Mobile Addiction Recovery System', 'MARS, Mobile Addiction Recovery System, is a system we helped develop with Tech Diversified to deliver long term support to alcoholics, addicts, and their family and recovery networks. This system has various features, which users can use to quickly locate recovery resources with just a tap, all while keeping their data secure and private.', 'Eduardo del Corral, Rick Stivers, Michael Senger', 3, 'Shane McNeese, Bartosz Swiech, Janindu Weerasuriya', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/AOslRAGV1N8', 'https://www.youtube.com/watch?v=AOslRAGV1N8', '2024-11-23', 'NO');
INSERT INTO `ShowcaseEntries` (`EntryID`, `Email`, `Name`, `ProjectTitle`, `ProjectDescription`, `Sponsor`, `NumberOfMembers`, `MemberNames`, `CourseNumber`, `Demo`, `Power`, `NDA`, `VideoLink`, `VideoLinkRaw`, `DateStamp`, `ShouldDisplay`) VALUES
(80, 'aalee10@asu.edu', 'Alexander Lee', 'CS/E-025 Expeditise - Website Development: Streamlining Access to Information and Services', 'Expeditise is an assistance based website meant to quickly find an expert to solve a user\'s problem.  The key difference with Expeditise is the usage of AI via the GPT API in order to automatically search for the best fit for a given task. The project focused on front-end web design and back-end connections to offer a seemless communication system.', 'Ali Sarabi, asarabi1@asu.edu', 5, 'Alexander Lee, Nengcong Guan, Luke Dujmic, Andy Vu, Jerin Joseph', 'CSE486, CSE424', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/pJo6w-79bu8&ab_channel', 'https://www.youtube.com/watch?v=pJo6w-79bu8&ab_channel=AlexanderLee', '2024-11-23', 'NO'),
(81, 'sozgur@asu.edu', 'Spencer Ozgur', 'CS/E-044 Local Grow Salads - Director', 'Served as Database Architect for LGS. Worked with SQL and Postgres to manage database.', 'Kamna Surjani', 1, 'Spencer Ozgur', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/odNBMXEnOXg', 'https://youtu.be/odNBMXEnOXg', '2024-11-23', 'YES'),
(82, 'aareddy1@asu.edu', 'Abhikya Reddy Ananth', 'CS/E-048 Local Grown Salads - LGS EcoSystem Customer Layer', 'The Local Grown Salads (LGS) project aims to create customer-facing applications for distributors, retailers, manufacturers, and consumers. These tools enable real-time quality checks, feedback, and seamless data integration. The project ensures scalability, security, and an improved user experience using modern technologies like React Native', 'Zale Tabakman', 4, 'Noah McClleland, Abhikya Reddy Ananth, Daniel Olma, Eyasu Abebe', 'CSE 424, CSE 486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/7NuvmpoC_xo', 'https://youtu.be/7NuvmpoC_xo', '2024-11-23', 'NO'),
(83, 'amellio5@asu.edu', 'Aften Elliott', 'CS/E-068 SCAI - ASU Capstone Judging Application', 'The ASU Capstone Judging Application is a web platform designed to judge different events happening within ASU.', 'Steven Osburn', 3, 'Aften Elliott, Bharathi Chikkala, Janvi Siddhapura', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/ozzlzX-GVPQ', 'https://www.youtube.com/watch?v=ozzlzX-GVPQ', '2024-11-23', 'YES'),
(84, 'mghasib@asu.edu', 'Majed Ghasib', 'CS/E-042 Local Grow Salads - Agronomist', 'The project involves developing a backend API to manage product packaging data by retrieving, adding, and displaying product and package details. It integrates data from the Product, Product Packaging, and related tables to ensure accurate connections between products and their associated packaging. The system aims to streamline the management and retrieval of product packaging information for further processing or display on a frontend application.', 'zale@localgrownfoods.ca', 1, 'Majed Ghasib', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/WLiMYpL4iV8', 'https://youtu.be/WLiMYpL4iV8', '2024-11-23', 'NO'),
(85, 'vpattela@asu.edu', 'Venkaata', 'CS/E-018 Center for Entrepreneurship and New Business Design - Housing Coordination', 'Our project involves creating a user-friendly website designed to connect Success Coaches and Housing Providers with Young Adults seeking housing. The platform will feature tools for listing housing options, filtering based on individual needs, and facilitating direct communication between providers and young adults. By streamlining the process, our website aims to support young adults in finding secure, suitable housing while improving collaboration between coaches and providers.', 'Larry Heitz', 5, 'Venkata Pattela, Kaylem Brown Malone, Nandini Singh,Christopher Hernandez, Duc Quang Tran', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/5VSFSLv0fds', 'https://youtu.be/5VSFSLv0fds', '2024-11-23', 'YES'),
(86, 'tpauga@asu.edu', 'Tuliloa Pauga', 'CS/E-085 VariableAI - VariableAI - Group A', 'This machine learning model involves analyzing essays to create detailed profiles by capturing features such as writing style, vocabulary usage, and tone. These profiles are then used to generate new writing content based on the identified characteristics. This combines natural language processing with creative AI techniques for personalized content generation.', 'Vikash Suthapali, Mahesh Gali', 3, 'Yi-Shiang Chiu, Zachary Hayes', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/aFdfVJdZw9w', 'https://youtu.be/aFdfVJdZw9w', '2024-11-23', 'NO'),
(87, 'jrtint@asu.edu', 'Joshua Tint', 'CS/E-035 Honeywell International - CICT Code migration from Visual Basic to Python using Gen AI', 'Our project focuses on automating the process of transferring data from C++ files into an MS Access database. We are developing AI tools to parse and organize the C++ data for seamless integration into the database. A key goal is to make the process user-friendly by building a simple graphical user interface (GUI) that highlights errors and assists with debugging. This system will improve efficiency by simplifying data transfer and ensuring flexibility for different data formats. The overall aim is to create an automated solution that minimizes manual effort while handling complex data structures effectively.', 'Brendan Tyler Lasley - Honeywell', 5, 'Joshua Tint, Wallace Yopp, Matthew Rutherford, Geoffrey Grossthal, Elise Macabou', 'CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/lleLODsAPDE', 'https://youtu.be/lleLODsAPDE', '2024-11-23', 'YES'),
(88, 'eaaguil3@asu.edu', 'Efren Aguilar', 'CS/E-028 Fourcher Technologies - Using AR to simulate the visual symptoms of dementia', 'The AR application we developed was designed to simulate the visual symptoms associated with dementia, enhancing understanding and empathy through immersive augmented reality experiences. Built for the Oculus Quest using Unity, the project incorporates features like dynamic symptom visualization and user-friendly interfaces to ensure accessibility and impact. Its development reflects a commitment to leveraging technology for educational and healthcare purposes.', 'Jordan Foucher', 5, 'Jack Hael, Agustin Ballesteros, Anushka Singh, Efren Aguilar, Joseph Kharzo', 'CSE 486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/0jSZpkBOApo', 'https://youtu.be/0jSZpkBOApo', '2024-11-23', 'YES'),
(89, 'mradmard@asu.edu', 'Haroon Radmard', 'CS/E-069 SCAI - ASU Capstone Time Management', 'The SCAI - ASU Capstone Time Management website is a centralized platform designed to streamline project management for capstone students, faculty, and sponsors. It offers core functionalities like managing projects, backlog items, sprints, and assignments, alongside collaboration tools such as communication pages and a calendar. This platform enhances transparency, accountability, and efficiency while addressing limitations of third-party tools.', 'Steven Osburn', 4, 'Madison McGuire, Haroon Radmard, Wejdan Alharthi, and Kelly Raines', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/R_S0b3FSa3s', 'https://www.youtube.com/watch?v=R_S0b3FSa3s', '2024-11-23', 'YES'),
(90, 'jwfrey@asu.edu', 'Jesse Frey', 'CS/E-005 Allennials at Work Inc. - Apple API Development for Publishing a WordPress Digital Magazine', 'A chatbot application for Allennials At Work that is ran locally on an employees machine. This application fetches answers from a secure server hosted by a Allenials at work server machine using Ollama 3.2.', 'Clair Kim', 3, 'Jesse Frey, Wenqi Liu, Timothy Gonzales', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/sRrLrIskODI', 'https://youtu.be/sRrLrIskODI', '2024-11-23', 'YES'),
(91, 'sberdia@asu.edu', 'Sohum Berdia', 'CS/E-037 InnC LLC - ArtVision Visualizer', 'Artwork AR Visualizer App that let\'s you generate and showcase artowork on your wall using your phone and AI.', 'Priyanka Khati', 2, 'Sohum Berdia, Derek Sanchez', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/kXSP6-LfBuA', 'https://youtu.be/kXSP6-LfBuA', '2024-11-23', 'NO'),
(92, 'cnguye61@asu.edu', 'Christina Nguyen', 'CS/E-051 Lower 22 Foundation Inc - Foxhole Lounge Mobile App Redesign', 'Our project involved redesigning a social media app for veterans. The goal is to create an easy to navigate application that helps foster a sense of community amongst veterans. The app will be available on both IOS and Android systems.', 'Adam Nance, Jennifer Mena', 4, 'Christina Nguyen, Jared Kitchen, Jasmine Miller, Trenton Cerny', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/uynR011qeM8', 'https://www.youtube.com/watch?v=uynR011qeM8', '2024-11-23', 'YES'),
(93, 'pgibbon4@asu.edu', 'Ping Gibbons', 'CS/E-057 Ofori - Enhancing Ofori\'s Website and Expanding Services', 'This web development project supervised by our sponsor Daniella Addison, involved enhancing the current functionalities of Ofori’s website by implementing a user feedback system and blog section. These additions aim to improve user engagement and satisfaction by facilitating effective communication between Ofori and its users.', 'Daniella Addison (oforibeautyy@gmail.com)', 2, 'Ping Gibbons, Aiden Robins', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/VDpOnAgutsE', 'https://youtu.be/VDpOnAgutsE', '2024-11-23', 'YES'),
(94, 'kkangas1@asu.edu', 'Kayla Kangas', 'CS/E-073 Self Justice Inc. - WordPress Website Development', 'Our project is Self Justice Inc, a website that allows Canadians to get a fair outcome in divorce proceedings without having to pay for an expensive attorney. The primary objective of this capstone project was to enhance the functionality, user experience, and performance of the Self Justice website.', 'Kyle Lacroix', 5, 'Alexander Epolite, Kayla Kangas, Jacky Situ, Victor Nyalita, Lawson Woods', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/0p2du3h_4zM', 'https://www.youtube.com/watch?v=0p2du3h_4zM', '2024-11-23', 'NO'),
(95, 'hkumar30@asu.edu', 'Harsh Kumar', 'CS/E-088 Velocity Tech Inc. - Zinio TalentHub', 'Zinio TalentHub is an innovative platform designed to streamline the process of connecting businesses with ERP-specialized contractors. With features like AI-powered resume parsing algorithms and contractor profile creation, Zinio ensures that companies can quickly find the best-fit contractors.', 'Strive Mazunga', 4, 'Harsh Kumar, Julia Kereszturi, Gunakarthik Naidu Lanka, Peshal Srinivas Kanamaluru', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/zHi9HdFdgHA', 'https://www.youtube.com/watch?v=zHi9HdFdgHA', '2024-11-23', 'YES'),
(96, 'rlin28@asu.edu', 'Ronald Lin', 'CS/E-023 DigiClips - Media Search Engine - Team 1', 'nhance user experience by providing a robust system for scouring the internet for media mention. By leveraging modern web technologies and cloud services Seamless and scalable solution for digital content management, empowering businesses and individuals to efficiently handle their media assets.', 'DigiClips Media Search Engine', 2, 'Ronald Lin, Rishon D. Netala', 'CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/JJd-DC17lxQ', 'https://youtu.be/JJd-DC17lxQ', '2024-11-23', 'YES'),
(97, 'wlee90@asu.edu', 'WeiChieh Lee', 'CS/E-017 Carnival Guide - Carnival Guide', 'A web platform for exploring global carnivals, purchasing Mas Camp costumes,  and booking merchandise.', 'L.Baptiste', 4, 'WeiChieh Lee, Suvan Kumar, Dan Nguyen, Isaiah Elder', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/CQM9g1Rgl-Y&t', 'https://www.youtube.com/watch?v=CQM9g1Rgl-Y&t=3s', '2024-11-23', 'NO'),
(98, 'spande49@asu.edu', 'Smrita Pandey', 'CS/E-053 Naralytics - Mobile App Re-Design (React Native)', 'Nara is to enhance emotional intelligence and relational well-being by helping users understand the emotions and perspectives of themselves and their loved ones. By creating characters and stories that mirror real-life conflicts, Nara provides insights into the reasons behind certain behaviors and potential reactions.', 'Gyou-Re Lee', 3, 'SMRITA PANDEY, MD SALMAN RAHMAN, RACHAEL WEBB', 'CSE 486, CSE 424', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/shorts', 'https://youtu.be/CEUED2B7Itc', '2024-11-23', 'NO'),
(99, 'nkamble@asu.edu', 'Nina Kamble', 'CS/E-052 Naralytics - iOS / Android App New Features', 'Naralytics enhances user engagement by exploring emotions and perspectives, with features like streamlined character creation, auto-save functionality, redesigned user interface and automated summary generation.', 'Gyou-Re Lee', 3, 'Nina Kamble, Saatvik Rao, Jay Patel', 'CSE 486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/L3Ka4IVir1o', 'https://youtu.be/L3Ka4IVir1o', '2024-11-23', 'NO');

-- --------------------------------------------------------

--
-- Table structure for table `ShowcaseEntries_Backup`
--

CREATE TABLE `ShowcaseEntries_Backup` (
  `EntryID` int NOT NULL DEFAULT '0',
  `Email` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `Name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `ProjectTitle` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `ProjectDescription` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `Sponsor` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `NumberOfMembers` int NOT NULL,
  `MemberNames` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `CourseNumber` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `Demo` enum('Yes','No') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `Power` enum('Yes','No') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `NDA` enum('Yes','No') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `VideoLink` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `VideoLinkRaw` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `DateStamp` date NOT NULL,
  `ShouldDisplay` enum('YES','NO') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `ShowcaseEntries_Backup`
--

INSERT INTO `ShowcaseEntries_Backup` (`EntryID`, `Email`, `Name`, `ProjectTitle`, `ProjectDescription`, `Sponsor`, `NumberOfMembers`, `MemberNames`, `CourseNumber`, `Demo`, `Power`, `NDA`, `VideoLink`, `VideoLinkRaw`, `DateStamp`, `ShouldDisplay`) VALUES
(1, 'lbirely@asu.edu', 'Lauren Birely', '23F-907 - Intel FCE Productivity', 'Intel\'s Fab Construction Enterprise Tool Installation team is dedicated to defining the maximum levels of efficiency of trade crews by doing direct observations. This will allow the productivity team to identify the leading causes of waste to then reallocate resources and/or educate our trade partners to become the most efficient and safest crews to install manufacturing equipment inside the new Fab.', 'Intel Fab Construction Enterprise', 2, 'Lauren Birely, Raquel Anchia Lopez', 'IEE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/-5-b8VlMPy4', 'https://youtu.be/-5-b8VlMPy4', '2024-04-09', 'YES'),
(2, 'lgmendo1@asu.edu', 'Louis Mendoza', 'SCAI CS/E-051 General Dynamics - Hardware Automated Test System', 'An application that allows General Dynamics engineers to remotely test various pieces of testing equipment. This is done either automatically through scripting or manually through a GUI interface that mimics a desired machine.', 'Carlos Davila', 4, 'Louis Mendoza, Justin Oswald, Isaac Wong, Angel Moreno', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/JAmMxLzh0PQ', 'https://youtu.be/JAmMxLzh0PQ', '2024-04-10', 'NO'),
(3, 'pjvargas@asu.edu', 'Peter Vargas', 'SCAI CS/E-105 PVCC Campus Wayfinding', 'This project involved creating a Bluetooth wayfinding app tailored for students navigating large campuses and complex buildings. The aim was to facilitate easy navigation to important landmarks like buildings, classrooms, water fountains, and food options, ultimately improving the overall campus experience for students.', 'Sapphire Labs', 5, 'Peter Vargas, Melissa Breguez, Erin McCann, Ethan Nicholson, Victor Truong', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/QdmW4Z_Z8nI', 'https://youtu.be/QdmW4Z_Z8nI', '2024-04-10', 'YES'),
(4, 'svwaltz@asu.edu', 'Sarah Waltz', 'SCAI CS/E-013 Astro Seed - GreenFlow: Designing User-Friendly and Aesthetically Pleasing Software for Effortless Terra Pod Operation', 'We are creating a web application designed to make it easier for users of the Astro Seed Terra Pod to make decisions about their crops quickly and effectively.', 'Vishnu Bhargav', 4, 'Abel Haddis, Sarah Waltz, Jawuan Lewis, Zhenggang Zhao', 'CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/kbofTj_2FGA', 'https://youtu.be/kbofTj_2FGA', '2024-04-10', 'YES'),
(5, 'aguha6@asu.edu', 'Alex Guha', 'SCAI CS/E-020 ASU SCAI - ChatGPT based Instructor-Assistant Web Application', 'A class-specific question answering system for students, utilizing machine learning and generative AI.', 'Professor Yinong Chen', 5, 'Alexander Guha, Adithya Chandramouli, Thomas Tung, Surya K. Rayala, and Ashish G. Deshpande', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/dNFJDLLJx2Y', 'https://youtu.be/dNFJDLLJx2Y', '2024-04-11', 'YES'),
(6, 'lolsen7@asu.edu', 'Laela Olsen', 'SCAI CS/E-016 Astro Seed - The Green Lens: Discovering Terra Pod\'s Flora', 'The Green Lens is a convolutional neural network model capable of identifying thirty different species of plants using image samples. In addition to creating this model, our team compiled a database of over 60,000 images for the purposes of training and testing the model. Using various machine learning techniques, the Green Lens model achieved an accuracy of 91.72% over all 30 classes.', 'Vishnu Bhargav', 5, 'Laela Olsen, Louys Gackstetter, Ian Carlson, Berenice Caudillo Mena, Keval Shah', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/nW6HEcHXv70', 'https://www.youtube.com/watch?v=nW6HEcHXv70', '2024-04-11', 'YES'),
(7, 'creaton1@asu.edu', 'Carter Eaton', '23F-011 MetroTown Asset Mgmt 1 - Searchable Database of Product Requirements', 'MCMsearch.com is an online searchable database that filters window models by performance specifications. It is accessible from anywhere and allows employees to search thousands of windows instantly.', 'Winnie Tang', 2, 'Carter Eaton, Mansour Alkhoori', 'IEE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/SdSml54whWw', 'https://www.youtube.com/watch?v=SdSml54whWw', '2024-04-11', 'YES'),
(8, 'mmayans@asu.edu', 'Madeline Mayans', 'SCAI CS/E-028 Building Black Youth Foundation - BBYF Children\'s Learning Game Development', 'We created a series of educational and inclusive games in collaboration with the Building Black Youth Foundation.', 'Building Black Youth Foundation', 5, 'William Bagley, Trent Buckallew, Nicholas Kelly, Madeline Mayans, Casey Randall', 'CSE 486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/yRigtIYtkrc', 'https://www.youtube.com/watch?v=yRigtIYtkrc', '2024-04-12', 'NO'),
(9, 'rwgore@asu.edu', 'Ryan Gore', 'SCAI CS/E-110 Sivworks - Investment Web Application', 'Investment web application that leverages probabilities to help users make and practice investment decisions and to guide them about what strategies to employ. Users will input investments and as they add more information to the platform, they will be able to see strategies for those investments. This project creates an application that is easy to read and easily navigable.', 'Tyler Reeves', 5, 'Dimitri Archipov, Leon Kwong, Sloan Cooney, Ryan Gore, and Jayden Ginoza', 'CSE486, CSE424', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/dRI-BMr6Ht8', 'https://www.youtube.com/watch?v=dRI-BMr6Ht8', '2024-04-12', 'YES'),
(10, 'ddalal3@asu.edu', 'Dylan Dalal', 'SCAI CS/E-069 Lenzya: A Geocentric creative talent platform', 'Lenzya is a geocentric creative talent platform that helps bridge the gap between freelancers and clients for in person events. Our goal is to eliminate the predatory pricing models of other freelancing platforms and allow for transparent booking and payments.', 'Ariane.Middel@asu.edu', 4, 'Dylan Dalal, James McCune, Waleed Khalid A Alsharari, David Parra', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/SM1vY9RqJww', 'https://youtu.be/SM1vY9RqJww', '2024-04-12', 'YES'),
(11, 'adbyers1@asu.edu', 'Andrew Byers', 'SCAI CS/E-073 Maricopa Association of Governments (MAG) - Sidewinder 2.0: IT Asset Management System', 'MAG\'s original application was a Windows Project Foundation using a C# application to house all functionality on both the front and back end, causing a multitude of issues. Over the past 2 semesters, our main goal was to transition this to an ASPNET MVC application to provide a nicer looking front end and a reworked SQL database to fix their improper data and potential data fixes.', 'Jon Christiansen', 4, 'Andrew Byers, Brandon Tsai, Ryan Powell, Christopher Merriman', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/LXLsQl19VDI', 'https://youtu.be/LXLsQl19VDI', '2024-04-12', 'YES'),
(12, 'dadunnin@asu.edu', 'Dylan Dunning', 'SCAI CS/E-054 GLOBAL SENSOR SYSTEMS INC - Trade Show Display', 'A Smart Braking solution for RC vehicles emulating Global Sensor Systems\' full-scale version to drive engagement at trade shows and expos.', 'Caroline Cooper', 4, 'Dylan Dunning, Pranav Mittal, Rock Palmer, Brandon Garciagomez', 'CSE486, CSE424', 'No', 'No', 'No', 'https://www.youtube.com/embed/3KfkEywVoaI', 'https://www.youtube.com/watch?v=3KfkEywVoaI', '2024-04-12', 'YES'),
(13, 'zschenk@asu.edu', 'Zane Schenk', 'SCAI CS/E-035 DEXTERS Lab, ASU School of Earth and Space Exploration - Website Development for Exoplanet Sciences and Outreach', 'Our full-stack project included building a website from scratch, optimizing and migrating a python script to an API, and database design. We were also responsible for testing and deploying our project using a custom Linux server on ASU\'s Tempe campus.', 'Lindsey Wiser', 3, 'Zane Schenk, Jagger Verdugo, Jason Roberts', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/wNGAy5W7YO4', 'https://www.youtube.com/watch?v=wNGAy5W7YO4', '2024-04-12', 'YES'),
(14, 'jthaley1@asu.edu', 'Jack Haley', 'SCAI CS/E-092 Northrop Grumman Corporation - LVBU SW Department - Web-based Interactive Launch Vehicle Coordinate System Model', 'A web-based application that models aerospace coordinate systems and simulates flight paths for a launch vehicle. This app gives users the ability to calculate transformation matrices between coordinate systems and export them for outside use.', 'Taylor Price', 4, 'Jack Haley, Ryan Cobourn, Michael Payne, Brian Lee', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/syhyRxCeje8', 'https://www.youtube.com/watch?v=syhyRxCeje8', '2024-04-13', 'NO'),
(15, 'scarcera@asu.edu', 'Salvatore Carcerano', 'SCAI CS/E-042 Fairmont Scottsdale Princess - Design and Implementation of an Automated Inventory Management System for Optimal Operations', 'his project aimed to enhance inventory management at Fairmont Scottsdale Princess by implementing innovative systems and optimizing warehouse layouts. We addressed challenges related to inefficient tracking, accessibility, and setup of event-specific inventory. Our approach involved centralizing inventory, implementing automated systems, and providing staff training.', 'Fairmont Scottsdale Princess - Michael Ortiz', 3, 'Salvatore Carcerano, Josue Hernandez Aguilar, Jash Sehul Daftary', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/xho9GCPHiYg', 'https://youtu.be/xho9GCPHiYg', '2024-04-13', 'YES'),
(16, 'traposo@asu.edu', 'Trevor Raposo', 'SCAI CS/E-090 NASA - Web-Based Game for Psyche 12L', 'A point and click adventure game that has the user playing as a NASA scientist taking part in NASA\'s Psyche mission. The game educates and informs players about the different components and factors of the Psyche mission through in-game items and item combination.', 'NASA Psyche Mission', 5, 'Trevor Raposo, Daniel Hahn, Keith Skabelund, Pramith Shivanna, Tuan Luong Luu', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/gP2qfefWOzI', 'https://youtu.be/gP2qfefWOzI', '2024-04-13', 'NO'),
(17, 'jchen449@asu.edu', 'Jeffrey Chen', 'SCAI CS/E-058 Hong Kong Kitchen II - Hong Kong Kitchen II Website', 'Our team was tasked with creating a new website for the restaurant brand Hong Kong Kitchen. The website was built with React and Node.js to create the front end of the webpage. This website is deployed in a live setting with a fully functional homepage, menu, contact page, and ordering system.', 'Jeff Zhen - jeffzhen1238@yahoo.com', 6, 'Charley Tran, Jeffrey Chen, Ka Wai Szeto, Ashwin Gulaya, Jeff Byju, Brian Zhen', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/AwkipKY_wdE', 'https://youtu.be/AwkipKY_wdE', '2024-04-13', 'YES'),
(18, 'jalbaffr@asu.edu', 'Joseph Albaffro', 'SCAI CS/E-061 Imperial Jade Crab Company - Automated Sorting of Premolt Crabs', 'The Imperial Jade Crab Company Team tackled the issue of preserving the ecosystem of Maine from invasive green crab species, while creating a market at the same time. This issue is laborious, time-consuming, and difficult to identify premolt crabs by hand. The Imperial Jade Crab Company project aims to use machine learning pattern recognition to identify the green crabs molting status in order to sort crabs in an efficient manner.', 'Joseph Manzo', 5, 'Nicolas Burton, Lleyton Ito, Ethan Tripp, Joseph Albaffro, Jared Riley', 'CSE 486, CSE 424', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/DTxDN-kS3Cw', 'https://www.youtube.com/watch?v=DTxDN-kS3Cw', '2024-04-13', 'NO'),
(19, 'tjmorga7@asu.edu', 'Tyler Morgan', 'SCAI CS/E-055 Global Sensor Systems Inc. - Automatic Reverse Braking demo truck', 'Developing a remote-controlled demo truck featuring an integrated sensor and braking system for effective product demonstrations at conferences. The truck will automatically brake while in reverse when approaching an object, this replicates Global Sensor Systems\' real-life product placed on large machinery.', 'Global Sensor Systems - Caroline Cooper', 4, 'Alexander Rickman, Alexander Hassler, Ahmed Alqahtan, Tyler Morgan', 'CSE424, 486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/-qTB5o-UC7Q', 'https://youtu.be/-qTB5o-UC7Q', '2024-04-13', 'YES'),
(20, 'asnicho5@asu.edu', 'Ashley Nichols', 'SCAI CS/E-057 Honeywell Aerospace - Improving flight plan routes based on Big Data and AI/ML', 'This project involved creating a feed forward neural network to improve ETA metrics for flights from Phoenix to Las Vegas. This process included creating webscrapers to gather opensource data, researching flight planning practices, and creating a UI to integrate the final product.', 'Sreenivasan Govindillam (KG)', 5, 'Ashley Nichols, Keya Gholap, Shardul Dhaul, John Baker, Yonatan Rosenbloom', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/M07-OR5vbDs', 'https://www.youtube.com/watch?v=M07-OR5vbDs', '2024-04-13', 'YES'),
(21, 'sagraw46@asu.edu', 'Shivank Agrawal', 'SCAI CS/E-094 OWL Integrations, Inc. - ClusterDuck Protocol Open Source Networks', 'For this project, we worked with the OWL foundation on the ClusterDuck Protocol on two key pieces of functionality. First, we created more sensor integrations to ease the new developer onboarding experience and ensure compatibility with different sensors. Second, we enhanced their SpaceDucks data analytics page by adding real-time visualizations and a prediction system for where the payload would land.', 'OWL Integrations, Inc', 4, 'Shivank Agrawal, Yagyna Gupta, Khoi Tran, Vikram Dattari', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/WvzVQm1VPuE', 'https://youtu.be/WvzVQm1VPuE', '2024-04-14', 'YES'),
(22, 'jjzhao@asu.edu', 'Jonathan Zhao', 'SCAI CS/E-052 General Dynamics - Redesign Xilinx FSBL, for the ZynqMP SoC, to Support Self-Extraction/Self-Relocation, Loading of Compressed Binary Images, and Re-Entry for Mode Switch Support', 'In this project, we redesign the Xilinx ZynqMP Ultrascale+ FSBL to support self-extraction and self-relocation. In addition, we implement a proof-of-concept for the full PetaLinux secure boot for ZCU106 and ZCU102.', 'Uzeir Karagic and Rene Bourquin', 3, 'Jonathan Zhao, Vincent Wu, Jeffery Frederic', 'CSE486, CSE424', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/SU1jbNSbLjk', 'https://www.youtube.com/watch?v=SU1jbNSbLjk', '2024-04-14', 'YES'),
(23, 'ltahan@asu.edu', 'Levi Tahan', '23F-004 Fairmont Princess Resort 4 - Laundry Department Process Optimization', 'At the Fairmont Scottsdale Princess, efficient handling of employee uniforms is required for smooth operations and maintaining a professional appearance. The Laundry Department Process Optimization project aimed to improve uniform valet operations, which is a crucial service for issuing, collecting, laundering, and storing employee uniforms', 'Michael Ortiz/Fairmont Scottsdale Princess', 3, 'Levi Tahan, Ariel Teo, Jose Castro', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/jxELYdEtm7g', 'https://youtu.be/jxELYdEtm7g', '2024-04-14', 'YES'),
(24, 'dsande30@asu.edu', 'Darius Sanders', 'SCAI CS/E-116 Yanbor LLC - Web Design of pages for OUReports.com', 'Redesign multiple web pages with modern UI functions and graphics. Implement functional features/changes to existing web pages.', 'Irina Yaroshevskaya', 5, 'Darius Sanders, Tong Guan, Craig Wilson, Jose Gamez, Bekzat Nadir', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/yG88OQt9jfg', 'https://youtu.be/yG88OQt9jfg', '2024-04-14', 'YES'),
(25, 'achuggi1@asu.edu', 'Aaron Huggins', 'SCAI CS/E-093 Omega Pediatrics - ChextrMD', 'A doctor-to-patient messaging mobile application to connect patients to their primary care practitioners.', 'Dr. Michael Nwaneri', 4, 'Aaron Huggins, Eron Ristich, Adam Hansen, Brody Heimlich', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/hcUT-QINzW8', 'https://youtu.be/hcUT-QINzW8', '2024-04-14', 'NO'),
(26, 'sanne7@asu.edu', 'Sriya Anne', 'SCAI CS/E-108 SeeMe LLC - SeeMe - Reach my full potential', 'SeeMe is a revolutionary new way of journaling. It gives you high-quality insights about yourself while letting you reflect on your day in less than 10 seconds.', 'Jannis Grimm', 5, 'Sriya Anne, Maci Rosenberger, Dina Helmi, Krisha Waghela, Sneha Dhanekula', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/DfsrCR17XSU', 'https://youtu.be/DfsrCR17XSU', '2024-04-14', 'NO'),
(27, 'yliu887@asu.edu', 'YungLing Liu', '23F-002 Fairmont Princess Resort 2 - Automated Inventory Management System', 'This project aims to develop an advanced Automated Inventory System that efficiently caters to the distinct needs of inventory management, engineering, and retail sales. The purpose is to streamline the hotel operations and enhance guest experience.', 'Michael Ortiz', 5, 'Ayham Dewan, Shrey Garg, YungLing Liu, Isha Sathe, Tejal Tripathi', 'CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/5xlQHEEs7Eo', 'https://youtu.be/5xlQHEEs7Eo', '2024-04-14', 'YES'),
(28, 'jschnulo@asu.edu', 'Kay Tuan Schnulo', 'SCAI CS/E-045 Fairmont Scottsdale Princess - Process Improvement & Sustainability Manager', 'Assist in information access from an extensive collection of PDF maintenance manuals for staff to help streamline operations via a chatbot that can understand diverse user queries and return accurate, relevant information from a multitude of document sources.', 'Michael Ortiz', 5, 'Kay Tuan Schnulo, Ellis Totman, Dhruv Anand, Punit Sai Arani, Patrick Lu', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/MxArrXMmzys', 'https://youtu.be/MxArrXMmzys', '2024-04-14', 'YES'),
(29, 'rtiwari6@asu.edu', 'Ravi Tiwari', 'SCAI CS/E-026 Bare metal coding with RISC-V on the Discovery kit', 'Our project integrates timekeeping features into the Discovery Kit system, enabling enthusiasts to explore microcontroller capabilities effortlessly. Through meticulous development and testing, we\'ve ensured accurate time display on both the console and the 7-segment display, fostering curiosity and innovation in the field.', 'Tim McCarthy', 3, 'Ravi Tiwari, Adam Amirkulov, Srinidhi Budhiraju', 'CSE 486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/6H_w6pCGM9I', 'https://youtu.be/6H_w6pCGM9I', '2024-04-14', 'YES'),
(30, 'acburto4@asu.edu', 'Alexander Burton', 'SCAI CS/E-008 Arizona State University, College of Health Solutions/Sun Devil Athletics - Athlete Management System for Sun Devil Athletics', 'We created an athlete management system for the ASU women\'s volleyball team. This includes a PowerBI dashboard showing important player and team stats alongside natural language analytics for easy interpretation and decision making. We also developed an injury prevention system in Python using predictive machine learning.', 'Alicia Montolva', 3, 'Sushrut Ghosal, Pavit Bagga, Alexander Burton', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/R0kekaxZVgY', 'https://youtu.be/R0kekaxZVgY', '2024-04-14', 'YES'),
(31, 'ngangrad@asu.edu', 'Navya Gangrade', 'SCAI CS/E-076 Mayo Clinic - Detecting the toxic in paper review and rewriting them in an encouraging and friendly tone.', 'Some reviews (especially those low score reviews) can be very discouraging (negative), which can lead to unintentional psychological damage (e.g. anxiety or depression) to the authors. Our goal here is to identify the toxicity in the initial paper review and edit the review which still maintains the feedback and suggestions of the initial review but written in a friendly and courageous tone.', 'Imon Banerjee, Man Luo', 5, 'Navya Gangrade, Ariadne Dimarogona, Hari Ramalingame, Rafael Gan, Brad Peterson', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/CDpQw8C6AJI', 'https://youtu.be/CDpQw8C6AJI', '2024-04-14', 'YES'),
(32, 'msmakh1@asu.edu', 'Mihika Makhija', 'SCAI CS/E-071 AI Empowerment Foundation - Music Generation with ML/AI', 'Our goal is to create a generative AI/ML tool that makes music. Users can input prompts to specify the genre, mood, and other parameters. Using this input, our model will generate a unique piece of music that aligns with the given requirements.', 'AI Empowerment Foundation', 5, 'Mihika Makhija, Brinda Chandran, Yuting Jiang, Yixuan Cheng, Fariah Hyder', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/nXM7TXK9J28', 'https://www.youtube.com/watch?v=nXM7TXK9J28', '2024-04-14', 'YES');

-- --------------------------------------------------------

--
-- Table structure for table `survey_entries`
--

CREATE TABLE `survey_entries` (
  `id` int NOT NULL,
  `email` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `projectTitle` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `projectDescription` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `sponsor` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `teamMemberNames` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `numberOfTeamMembers` int DEFAULT NULL,
  `major` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `demo` tinyint(1) DEFAULT NULL,
  `power` tinyint(1) DEFAULT NULL,
  `nda` tinyint(1) DEFAULT NULL,
  `youtubeLink` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `teams_and_teams_ids___sheet1`
--

CREATE TABLE `teams_and_teams_ids___sheet1` (
  `Team ID` varchar(10) DEFAULT NULL,
  `Teams` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `teams_and_teams_ids___sheet1`
--

INSERT INTO `teams_and_teams_ids___sheet1` (`Team ID`, `Teams`) VALUES
('CS/E-001', 'ABC Academy of Music - ABC Academy of Music • Custom Business Management Software'),
('CS/E-002', 'ABC Academy of Music - CLIENT SELF-MANAGEMENT • Hinna: Small Business Management Software'),
('CS/E-003', 'Ada Analytics - Website Development'),
('CS/E-004', 'Alcove Ridge Consulting LLC - Unique experience to work on a cutting edge Fintech platform'),
('CS/E-005', 'Allennials at Work Inc. - Apple API Development for Publishing a WordPress Digital Magazine'),
('CS/E-006', 'AOKMarketing.com - Chattable'),
('CS/E-007', 'Arizona State University - Quantum Computing Tool for Education'),
('CS/E-008', 'ASU - Smart Knowledge Navigation and Discovery Platform'),
('CS/E-009', 'ASU Capstone Showcase'),
('CS/E-010', 'ASU ECEE - Logic Tutor for the Web Phase 2'),
('CS/E-011', 'ASU SCAI - Web-Based RISC V Architecture Emulator in VIPLE Environment'),
('CS/E-012', 'BetterEDU - BetterEDU'),
('CS/E-013', 'Bit Space Development'),
('CS/E-014', 'BizBridge.io - BizBridge: Building out an AI-Agentic Workflow to Sell Small Businesses!'),
('CS/E-015', 'Capstone Project Submission Group - ASU'),
('CS/E-016', 'Capstone Project Ticketing System'),
('CS/E-017', 'Carnival Guide - Carnival Guide'),
('CS/E-018', 'Center for Entrepreneurship and New Business Design - Housing Coordination'),
('CS/E-019', 'Coconut CubeSat Software - Student Project'),
('CS/E-020', 'Contak - Kinda Famous: Music Adventure Role Playing Video Game'),
('CS/E-021', 'DigiClips  - DEBUG OPTION EMAIL ALERTS FRONT END SEARCH ENGINE TESTING'),
('CS/E-022', 'DigiClips  - DigiClips Media Search Engine'),
('CS/E-023', 'DigiClips - Media Search Engine - Team 1'),
('CS/E-024', 'DigiClips - Media Search Engine - Team 2'),
('CS/E-025', 'Expeditise - Website Development: Streamlining Access to Information and Services'),
('CS/E-026', 'Favoland - AI-driven beauty ingredient database and rating system'),
('CS/E-027', 'Fourcher Technologies - Tracking bees using AI'),
('CS/E-028', 'Fourcher Technologies - Using AR to simulate the visual symptoms of dementia'),
('CS/E-029', 'General Dynamics Mission Systems - Prototyping alternate GIS solutions for real-time scenarios'),
('CS/E-030', 'General Dynamics Mission Systems - Quantum Image Denoising using computational basis states'),
('CS/E-031', 'GLOBAL SENSOR SYSTEMS INC - Trade Show Display'),
('CS/E-032', 'Hawkeye Early Detection System - Hawkeye Early Detection System'),
('CS/E-033', 'Honeywell International - Adaptive Announcement System'),
('CS/E-034', 'Honeywell International - Build a block chain-based solution for UAM Data management.'),
('CS/E-035', 'Honeywell International - CICT Code migration from Visual Basic to Python using Gen AI'),
('CS/E-036', 'InnC LLC - ArtVision Renderer'),
('CS/E-037', 'InnC LLC - ArtVision Visualizer'),
('CS/E-038', 'IT Partner LLC.-Software Development - Licensing Recommendation Tool for Microsoft 365'),
('CS/E-039', 'Jo Clark, CEO - Circle.ooo AI Initiative'),
('CS/E-040', 'Judy.ai - Judy.ai for Healthcare'),
('CS/E-041', 'KnowQuest Inc. - Web or Native App UI/UX Development'),
('CS/E-042', 'Local Grow Salads - Agronomist'),
('CS/E-043', 'Local Grow Salads - Assembly'),
('CS/E-044', 'Local Grow Salads - Director'),
('CS/E-045', 'Local Grow Salads - Grower'),
('CS/E-046', 'Local Grow Salads - Inspector'),
('CS/E-047', 'Local Grown Salads - LGS EcoSystem - Network'),
('CS/E-048', 'Local Grown Salads - LGS EcoSystem Customer Layer'),
('CS/E-049', 'Lotus - Addiction Therapy Inc -web /mobile development '),
('CS/E-050', 'Lotus Addiction Therapy Inc - Lotus'),
('CS/E-051', 'Lower 22 Foundation Inc - Foxhole Lounge Mobile App Redesign'),
('CS/E-052', 'Naralytics - iOS / Android App New Features'),
('CS/E-053', 'Naralytics - Mobile App Re-Design (React Native)'),
('CS/E-054', 'Naralytics - NLP & Classification Model Optimization'),
('CS/E-055', 'Northrop Grumman - Finance Reporting Tool'),
('CS/E-056', 'Nowhere Collective - A Circular Marketplace for Upcycling Makers and Conscious Consumers'),
('CS/E-057', 'Ofori - Enhancing Ofori\'s Website and Expanding Services'),
('CS/E-058', 'Omega Pediatrics - Mobile Messaging App for Doctors - AWS/ReactNative/DynamoDB'),
('CS/E-059', 'OneDrug Inc. - Smart Mobile and Web Health Application for Integrated Healthcare'),
('CS/E-060', 'Pathscape - Pathscape Mobile App Development'),
('CS/E-061', 'Personal Project - Works for Northrop Grumman Corp - Digital Video Maipulation'),
('CS/E-062', 'Points Africa - Points Africa Mobile App Development'),
('CS/E-063', 'Prescott Electric Motors - Electric Motor Monitoring System'),
('CS/E-064', 'QuestStone LLC. - Slack App + Microsoft Teams App Development'),
('CS/E-065', 'Reality Articulated - Empath-Dashboard'),
('CS/E-066', 'Reality Articulated - Empath-iOS'),
('CS/E-067', 'Rock Climbing Routemaking AI - Student Project'),
('CS/E-068', 'SCAI - ASU Capstone Judging Application'),
('CS/E-069', 'SCAI - ASU Capstone Time Management'),
('CS/E-070', 'School of Computing and Augmented Intelligence  - Interactive 3D Data Analytics Learning Environment'),
('CS/E-071', 'School of Computing and Augmented Intelligence  - Smart Sound-to-Speech Interpreter for Security and Notification Systems'),
('CS/E-072', 'School of Geog Science & Urban Planning, ASU - Automated Detection of Traffic and Street Environments'),
('CS/E-073', 'Self Justice Inc. - WordPress Website Development'),
('CS/E-074', 'Sense Science Lab LTD - Human AI Collaborative Drawing Tool Development'),
('CS/E-075', 'Shoptaki  - CEO'),
('CS/E-076', 'Shoptaki - Smartchain next evolution of distributed network'),
('CS/E-077', 'Shoptaki - Smartid universal identity'),
('CS/E-078', 'StayWell - StayWell Medical Habit Tracker Mobile App'),
('CS/E-079', 'Table Ready - AI-enhanced social media post generator and Infra Red seating detection system'),
('CS/E-080', 'Tech Diversified - MARS Mobile Addiction Recovery System'),
('CS/E-081', 'The Clean Divorce - Use technology to simplify & modernize divorce to support families'),
('CS/E-082', 'Toyz Electronics - Game Developer for Online Learning Platform'),
('CS/E-083', 'VariableAI - VariableAI - Data Team'),
('CS/E-084', 'VariableAI - VariableAI - Full Stack Team'),
('CS/E-085', 'VariableAI - VariableAI - Group A'),
('CS/E-086', 'VariableAI - VariableAI - Model Team'),
('CS/E-087', 'Velocified - Lean Enterprise LMS & Tracking Platform'),
('CS/E-088', 'Velocity Tech Inc. - Zinio TalentHub'),
('CS/E-089', 'Yanbor LLC - Develop testing system for the site OUReports.com'),
('IEE-001', 'Goodyear 1: COI'),
('IEE-002', 'Goodyear 2: TraCtion'),
('IEE-003', 'Goodyear 3: Process Modeling'),
('IEE-004', 'Abbott: Equipment Changeover'),
('IEE-005', 'L3Harris: Power Supply'),
('IEE-006', 'ASU Athletics 1: Readiness Score'),
('IEE-007', 'ASU Athletics 2: Data Analysis'),
('IEE-008', 'ASU Earth and Space: Social Media'),
('IEE-009', 'ASU Earth and Space: Exhibit Planning'),
('IEE-010', 'Amkor Material Cost Estimator');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin_pass_hash`
--
ALTER TABLE `admin_pass_hash`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `ShowcaseEntries`
--
ALTER TABLE `ShowcaseEntries`
  ADD PRIMARY KEY (`EntryID`);

--
-- Indexes for table `survey_entries`
--
ALTER TABLE `survey_entries`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin_pass_hash`
--
ALTER TABLE `admin_pass_hash`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `ShowcaseEntries`
--
ALTER TABLE `ShowcaseEntries`
  MODIFY `EntryID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=100;

--
-- AUTO_INCREMENT for table `survey_entries`
--
ALTER TABLE `survey_entries`
  MODIFY `id` int NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
