-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: May 30, 2024 at 03:10 PM
-- Server version: 5.7.23-23
-- PHP Version: 8.1.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `jmtlqnmy_CapstoneProjects`
--

-- --------------------------------------------------------

--
-- Table structure for table `ShowcaseEntries`
--

CREATE TABLE `ShowcaseEntries` (
  `EntryID` int(11) NOT NULL,
  `Email` text COLLATE utf8_unicode_ci NOT NULL,
  `Name` text COLLATE utf8_unicode_ci NOT NULL,
  `ProjectTitle` text COLLATE utf8_unicode_ci NOT NULL,
  `ProjectDescription` text COLLATE utf8_unicode_ci NOT NULL,
  `Sponsor` text COLLATE utf8_unicode_ci NOT NULL,
  `NumberOfMembers` int(11) NOT NULL,
  `MemberNames` text COLLATE utf8_unicode_ci NOT NULL,
  `CourseNumber` text COLLATE utf8_unicode_ci NOT NULL,
  `Demo` text COLLATE utf8_unicode_ci NOT NULL,
  `Power` text COLLATE utf8_unicode_ci NOT NULL,
  `NDA` text COLLATE utf8_unicode_ci NOT NULL,
  `VideoLink` text COLLATE utf8_unicode_ci NOT NULL,
  `VideoLinkRaw` text COLLATE utf8_unicode_ci NOT NULL,
  `DateStamp` date NOT NULL,
  `ShouldDisplay` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Whether it should display on the main page - YES/NO'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Team info collected from registration survey';

--
-- Dumping data for table `ShowcaseEntries`
--

INSERT INTO `ShowcaseEntries` (`EntryID`, `Email`, `Name`, `ProjectTitle`, `ProjectDescription`, `Sponsor`, `NumberOfMembers`, `MemberNames`, `CourseNumber`, `Demo`, `Power`, `NDA`, `VideoLink`, `VideoLinkRaw`, `DateStamp`, `ShouldDisplay`) VALUES
(1, 'lbirely@asu.edu', 'Lauren Birely', '23F-907 - Intel FCE Productivity', 'Intel\'s Fab Construction Enterprise Tool Installation team is dedicated to defining the maximum levels of efficiency of trade crews by doing direct observations. This will allow the productivity team to identify the leading causes of waste to then reallocate resources and/or educate our trade partners to become the most efficient and safest crews to install manufacturing equipment inside the new Fab.', 'Intel Fab Construction Enterprise', 2, 'Lauren Birely, Raquel Anchia Lopez', 'IEE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/-5-b8VlMPy4', 'https://youtu.be/-5-b8VlMPy4', '2024-04-09', 'YES'),
(2, 'lgmendo1@asu.edu', 'Louis Mendoza', 'SCAI CS/E-051 General Dynamics - Hardware Automated Test System', 'An application that allows General Dynamics engineers to remotely test various pieces of testing equipment. This is done either automatically through scripting or manually through a GUI interface that mimics a desired machine.', 'Carlos Davila', 4, 'Louis Mendoza, Justin Oswald, Isaac Wong, Angel Moreno', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/JAmMxLzh0PQ', 'https://youtu.be/JAmMxLzh0PQ', '2024-04-10', 'NO'),
(3, 'pjvargas@asu.edu', 'Peter Vargas', 'SCAI CS/E-105 PVCC Campus Wayfinding', 'This project involved creating a Bluetooth wayfinding app tailored for students navigating large campuses and complex buildings. The aim was to facilitate easy navigation to important landmarks like buildings, classrooms, water fountains, and food options, ultimately improving the overall campus experience for students.', 'Sapphire Labs', 5, 'Peter Vargas, Melissa Breguez, Erin McCann, Ethan Nicholson, Victor Truong', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/QdmW4Z_Z8nI', 'https://youtu.be/QdmW4Z_Z8nI', '2024-04-10', 'YES'),
(4, 'svwaltz@asu.edu', 'Sarah Waltz', 'SCAI CS/E-013 Astro Seed - GreenFlow: Designing User-Friendly and Aesthetically Pleasing Software for Effortless Terra Pod Operation', 'We are creating a web application designed to make it easier for users of the Astro Seed Terra Pod to make decisions about their crops quickly and effectively.', 'Vishnu Bhargav', 4, 'Abel Haddis, Sarah Waltz, jawuan Lewis, Zhenggang_Zhao', 'CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/kbofTj_2FGA', 'https://youtu.be/kbofTj_2FGA', '2024-04-10', 'YES'),
(5, 'aguha6@asu.edu', 'Alex Guha', 'SCAI CS/E-020 ASU SCAI - ChatGPT based Instructor-Assistant Web Application', 'A class-specific question answering system for students, utilizing machine learning and generative AI.', 'Professor Yinong Chen', 5, 'Alexander Guha, Adithya Chandramouli, Thomas Tung, Surya K. Rayala, and Ashish G. Deshpande', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/dNFJDLLJx2Y', 'https://youtu.be/dNFJDLLJx2Y', '2024-04-11', 'YES'),
(6, 'lolsen7@asu.edu', 'Laela Olsen', 'SCAI CS/E-016 Astro Seed - The Green Lens: Discovering Terra Pod\'s Flora', 'The Green Lens is a convolutional neural network model capable of identifying thirty different species of plants using image samples. In addition to creating this model, our team compiled a database of over 60,000 images for the purposes of training and testing the model. Using various machine learning techniques, the Green Lens model achieved an accuracy of 91.72% over all 30 classes.', 'Vishnu Bhargav', 5, 'Laela Olsen, Louys Gackstetter, Ian Carlson, Berenice Caudillo Mena, Keval Shah', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/nW6HEcHXv70', 'https://www.youtube.com/watch?v=nW6HEcHXv70', '2024-04-11', 'YES'),
(7, 'creaton1@asu.edu', 'Carter Eaton', '23F-011 MetroTown Asset Mgmt 1 - Searchable Database of Product Requirements', 'MCMsearch.com is an online searchable database that filters window models by performance specifications. It is accessible from anywhere and allows employees to search thousands of windows instantly.', 'Winnie Tang', 2, 'Carter Eaton, Mansour Alkhoori', 'IEE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/SdSml54whWw', 'https://www.youtube.com/watch?v=SdSml54whWw', '2024-04-11', 'YES'),
(8, 'mmayans@asu.edu', 'Madeline Mayans', 'SCAI CS/E-028 Building Black Youth Foundation - BBYF Children\'s Learning Game Development', 'We created a series of educational and inclusive games in collaboration with the Building Black Youth Foundation.', 'Building Black Youth Foundation', 5, 'William Bagley, Trent Buckallew, Nicholas Kelly, Madeline Mayans, Casey Randall', 'CSE 486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/yRigtIYtkrc', 'https://www.youtube.com/watch?v=yRigtIYtkrc', '2024-04-12', 'NO'),
(9, 'rwgore@asu.edu', 'Ryan Gore', 'SCAI CS/E-110 Sivworks - Investment Web Application', 'Investment web application that leverages probabilities to help users make and practice investment decisions and to guide them about what strategies to employ. Users will input investments and as they add more information to the platform, they will be able to see strategies for those investments. This project creates an application that is easy to read and easily navigable.', 'Tyler Reeves', 5, 'Dimitri Archipov, Leon Kwong, Sloan Cooney, Ryan Gore, and Jayden Ginoza', 'CSE486, CSE424', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/dRI-BMr6Ht8', 'https://www.youtube.com/watch?v=dRI-BMr6Ht8', '2024-04-12', 'YES'),
(10, 'ddalal3@asu.edu', 'Dylan Dalal', 'SCAI CS/E-069 Lenzya: A Geocentric creative talent platform', 'Lenzya is a geocentric creative talent platform that helps bridge the gap between freelancers and clients for in person events. Our goal is to eliminate the predatory pricing models of other freelancing platforms and allow for transparent booking and payments.', 'Ariane.Middel@asu.edu', 4, 'Dylan Dalal, James McCune, Waleed Khalid A Alsharari, David Parra', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/SM1vY9RqJww', 'https://youtu.be/SM1vY9RqJww', '2024-04-12', 'YES'),
(11, 'adbyers1@asu.edu', 'Andrew Byers', 'SCAI CS/E-073 Maricopa Association of Governments (MAG) - Sidewinder 2.0: IT Asset Management System', 'MAG\'s original application was a Windows Project Foundation using a C# application to house all functionality on both the front and back end, causing a multitude of issues. Over the past 2 semesters, our main goal was to transition this to an ASPNET MVC application to provide a nicer looking front end and a reworked SQL database to fix their improper data and potential data fixes.', 'Jon Christiansen', 4, 'Andrew Byers, Brandon Tsai, Ryan Powell, Christopher Merriman', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/LXLsQl19VDI', 'https://youtu.be/LXLsQl19VDI', '2024-04-12', 'YES'),
(12, 'dadunnin@asu.edu', 'Dylan Dunning', 'SCAI CS/E-054 GLOBAL SENSOR SYSTEMS INC - Trade Show Display', 'A Smart Braking solution for RC vehicles emulating Global Sensor Systems\' full-scale version to drive engagement at trade shows and expos.', 'Caroline Cooper', 4, 'Dylan Dunning, Pranav Mittal, Rock Palmer, Brandon Garciagomez', 'CSE486, CSE424', 'No', 'No', 'No', 'https://www.youtube.com/embed/3KfkEywVoaI', 'https://www.youtube.com/watch?v=3KfkEywVoaI', '2024-04-12', 'YES'),
(13, 'zschenk@asu.edu', 'Zane Schenk', 'SCAI CS/E-035 DEXTERS Lab, ASU School of Earth and Space Exploration - Website Development for Exoplanet Sciences and Outreach', 'Our full-stack project included building a website from scratch, optimizing and migrating a python script to an API, and database design. We were also responsible for testing and deploying our project using a custom Linux server on ASU\'s Tempe campus.', 'Lindsey Wiser', 3, 'Zane Schenk, Jagger Verdugo, Jason Roberts', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/wNGAy5W7YO4', 'https://www.youtube.com/watch?v=wNGAy5W7YO4', '2024-04-12', 'YES'),
(14, 'jthaley1@asu.edu', 'Jack Haley', 'SCAI CS/E-092 Northrop Grumman Corporation - LVBU SW Department - Web-based Interactive Launch Vehicle Coordinate System Model', 'A web-based application that models aerospace coordinate systems and simulates flight paths for a launch vehicle. This app gives users the ability to calculate transformation matrices between coordinate systems and export them for outside use.', 'Taylor Price', 4, 'Jack Haley, Ryan Cobourn, Michael Payne, Brian Lee', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/syhyRxCeje8', 'https://www.youtube.com/watch?v=syhyRxCeje8', '2024-04-13', 'NO'),
(15, 'scarcera@asu.edu', 'Salvatore Carcerano', 'SCAI CS/E-042 Fairmont Scottsdale Princess - Design and Implementation of an Automated Inventory Management System for Optimal Operations', 'his project aimed to enhance inventory management at Fairmont Scottsdale Princess by implementing innovative systems and optimizing warehouse layouts. We addressed challenges related to inefficient tracking, accessibility, and setup of event-specific inventory. Our approach involved centralizing inventory, implementing automated systems, and providing staff training.', 'Fairmont Scottsdale Princess - Michael Ortiz', 3, 'Salvatore Carcerano, Josue Hernandez Aguilar, Jash Sehul Daftary', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/xho9GCPHiYg', 'https://youtu.be/xho9GCPHiYg', '2024-04-13', 'YES'),
(16, 'traposo@asu.edu', 'Trevor Raposo', 'SCAI CS/E-090 NASA - Web-Based Game for Psyche 12L', 'A point and click adventure game that has the user playing as a NASA scientist taking part in NASA\'s Psyche mission. The game educates and informs players about the different components and factors of the Psyche mission through in-game items and item combination.', 'NASA Psyche Mission', 5, 'Trevor Raposo, Daniel Hahn, Keith Skabelund, Pramith Shivanna, Tuan Luong Luu', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/gP2qfefWOzI', 'https://youtu.be/gP2qfefWOzI', '2024-04-13', 'NO'),
(17, 'jchen449@asu.edu', 'Jeffrey Chen', 'SCAI CS/E-058 Hong Kong Kitchen II - Hong Kong Kitchen II Website', 'Our team was tasked with creating a new website for the restaurant brand Hong Kong Kitchen. The website was built with React and Node.js to create the front end of the webpage. This website is deployed in a live setting with a fully functional homepage, menu, contact page, and ordering system.', 'Jeff Zhen - jeffzhen1238@yahoo.com', 6, 'Charley Tran, Jeffrey Chen, Ka Wai Szeto, Ashwin Gulaya, Jeff Byju, Brian Zhen', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/AwkipKY_wdE', 'https://youtu.be/AwkipKY_wdE', '2024-04-13', 'YES'),
(18, 'jalbaffr@asu.edu', 'Joseph Albaffro', 'SCAI CS/E-061 Imperial Jade Crab Company - Automated Sorting of Premolt Crabs', 'The Imperial Jade Crab Company Team tackled the issue of preserving the ecosystem of Maine from invasive green crab species, while creating a market at the same time. This issue is laborious, time-consuming, and difficult to identify premolt crabs by hand. The Imperial Jade Crab Company project aims to use machine learning pattern recognition to identify the green crabs molting status in order to sort crabs in an efficient manner.', 'Joseph Manzo', 5, 'Nicolas Burton, Lleyton Ito, Ethan Tripp, Joseph Albaffro, Jared Riley', 'CSE 486, CSE 424', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/DTxDN-kS3Cw', 'https://www.youtube.com/watch?v=DTxDN-kS3Cw', '2024-04-13', 'NO'),
(19, 'tjmorga7@asu.edu', 'Tyler Morgan', 'SCAI CS/E-055 Global Sensor Systems Inc. - Automatic Reverse Braking demo truck', 'Developing a remote-controlled demo truck featuring an integrated sensor and braking system for effective product demonstrations at conferences. The truck will automatically brake while in reverse when approaching an object, this replicates Global Sensor Systems\' real-life product placed on large machinery.', 'Global Sensor Systems - Caroline Cooper', 4, 'Alexander Rickman, Alexander Hassler, Ahmed Alqahtan, Tyler Morgan', 'CSE424, 486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/-qTB5o-UC7Q', 'https://youtu.be/-qTB5o-UC7Q', '2024-04-13', 'YES'),
(20, 'asnicho5@asu.edu', 'Ashley Nichols', 'SCAI CS/E-057 Honeywell Aerospace - Improving flight plan routes based on Big Data and AI/ML', 'This project involved creating a feed forward neural network to improve ETA metrics for flights from Phoenix to Las Vegas. This process included creating webscrapers to gather opensource data, researching flight planning practices, and creating a UI to integrate the final product.', 'Sreenivasan Govindillam (KG)', 5, 'Ashley Nichols, Keya Gholap, Shardul Dhaul, John Baker, Yonatan Rosenbloom', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/M07-OR5vbDs', 'https://www.youtube.com/watch?v=M07-OR5vbDs', '2024-04-13', 'YES'),
(21, 'sagraw46@asu.edu', 'Shivank Agrawal', 'SCAI CS/E-094 OWL Integrations, Inc. - ClusterDuck Protocol Open Source Networks', 'For this project, we worked with the OWL foundation on the ClusterDuck Protocol on two key pieces of functionality. First, we created more sensor integrations to ease the new developer onboarding experience and ensure compatibility with different sensors. Second, we enhanced their SpaceDucks data analytics page by adding real-time visualizations and a prediction system for where the payload would land.', 'OWL Integrations, Inc', 4, 'Shivank Agrawal, Yagyna Gupta, Khoi Tran, Vikram Dattari', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/WvzVQm1VPuE', 'https://youtu.be/WvzVQm1VPuE', '2024-04-14', 'YES'),
(22, 'jjzhao@asu.edu', 'Jonathan Zhao', 'SCAI CS/E-052 General Dynamics - Redesign Xilinx FSBL, for the ZynqMP SoC, to Support Self-Extraction/Self-Relocation, Loading of Compressed Binary Images, and Re-Entry for Mode Switch Support', 'In this project, we redesign the Xilinx ZynqMP Ultrascale+ FSBL to support self-extraction and self-relocation. In addition, we implement a proof-of-concept for the full PetaLinux secure boot for ZCU106 and ZCU102.', 'Uzeir Karagic and Rene Bourquin', 3, 'Jonathan Zhao, Vincent Wu, Jeffery Frederic', 'CSE486, CSE424', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/SU1jbNSbLjk', 'https://www.youtube.com/watch?v=SU1jbNSbLjk', '2024-04-14', 'YES'),
(23, 'ltahan@asu.edu', 'Levi Tahan', '23F-004 Fairmont Princess Resort 4 - Laundry Department Process Optimization', 'At the Fairmont Scottsdale Princess, efficient handling of employee uniforms is required for smooth operations and maintaining a professional appearance. The Laundry Department Process Optimization project aimed to improve uniform valet operations, which is a crucial service for issuing, collecting, laundering, and storing employee uniforms', 'Michael Ortiz/Fairmont Scottsdale Princess', 3, 'Levi Tahan, Ariel Teo, Jose Castro', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/jxELYdEtm7g', 'https://youtu.be/jxELYdEtm7g', '2024-04-14', 'YES'),
(24, 'dsande30@asu.edu', 'Darius Sanders', 'SCAI CS/E-116 Yanbor LLC - Web Design of pages for OUReports.com', 'Redesign multiple web pages with modern UI functions and graphics. Implement functional features/changes to existing web pages.', 'Irina Yaroshevskaya', 5, 'Darius Sanders, Tong Guan, Craig Wilson, Jose Gamez, Bekzat Nadir', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/yG88OQt9jfg', 'https://youtu.be/yG88OQt9jfg', '2024-04-14', 'YES'),
(25, 'achuggi1@asu.edu', 'Aaron Huggins', 'SCAI CS/E-093 Omega Pediatrics - ChextrMD', 'A doctor-to-patient messaging mobile application to connect patients to their primary care practitioners.', 'Dr. Michael Nwaneri', 4, 'Aaron Huggins, Eron Ristich, Adam Hansen, Brody Heimlich', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/hcUT-QINzW8', 'https://youtu.be/hcUT-QINzW8', '2024-04-14', 'NO'),
(26, 'sanne7@asu.edu', 'Sriya Anne', 'SCAI CS/E-108 SeeMe LLC - SeeMe - Reach my full potential', 'SeeMe is a revolutionary new way of journaling. It gives you high-quality insights about yourself while letting you reflect on your day in less than 10 seconds.', 'Jannis Grimm', 5, 'Sriya Anne, Maci Rosenberger, Dina Helmi, Krisha Waghela, Sneha Dhanekula', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/DfsrCR17XSU', 'https://youtu.be/DfsrCR17XSU', '2024-04-14', 'NO'),
(27, 'yliu887@asu.edu', 'YungLing Liu', '23F-002 Fairmont Princess Resort 2 - Automated Inventory Management System', 'This project aims to develop an advanced Automated Inventory System that efficiently caters to the distinct needs of inventory management, engineering, and retail sales. The purpose is to streamline the hotel operations and enhance guest experience.', 'Michael Ortiz', 5, 'Ayham Dewan, Shrey Garg, YungLing Liu, Isha Sathe, Tejal Tripathi', 'CSE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/5xlQHEEs7Eo', 'https://youtu.be/5xlQHEEs7Eo', '2024-04-14', 'YES'),
(28, 'jschnulo@asu.edu', 'Kay Tuan Schnulo', 'SCAI CS/E-045 Fairmont Scottsdale Princess - Process Improvement & Sustainability Manager', 'Assist in information access from an extensive collection of PDF maintenance manuals for staff to help streamline operations via a chatbot that can understand diverse user queries and return accurate, relevant information from a multitude of document sources.', 'Michael Ortiz', 5, 'Kay Tuan Schnulo, Ellis Totman, Dhruv Anand, Punit Sai Arani, Patrick Lu', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/MxArrXMmzys', 'https://youtu.be/MxArrXMmzys', '2024-04-14', 'YES'),
(29, 'rtiwari6@asu.edu', 'Ravi Tiwari', 'SCAI CS/E-026 Bare metal coding with RISC-V on the Discovery kit', 'Our project integrates timekeeping features into the Discovery Kit system, enabling enthusiasts to explore microcontroller capabilities effortlessly. Through meticulous development and testing, we\'ve ensured accurate time display on both the console and the 7-segment display, fostering curiosity and innovation in the field.', 'Tim McCarthy', 3, 'Ravi Tiwari, Adam Amirkulov, Srinidhi Budhiraju', 'CSE 486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/6H_w6pCGM9I', 'https://youtu.be/6H_w6pCGM9I', '2024-04-14', 'YES'),
(30, 'acburto4@asu.edu', 'Alexander Burton', 'SCAI CS/E-008 Arizona State University, College of Health Solutions/Sun Devil Athletics - Athlete Management System for Sun Devil Athletics', 'We created an athlete management system for the ASU women\'s volleyball team. This includes a PowerBI dashboard showing important player and team stats alongside natural language analytics for easy interpretation and decision making. We also developed an injury prevention system in Python using predictive machine learning.', 'Alicia Montolva', 3, 'Sushrut Ghosal, Pavit Bagga, Alexander Burton', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/R0kekaxZVgY', 'https://youtu.be/R0kekaxZVgY', '2024-04-14', 'YES'),
(31, 'ngangrad@asu.edu', 'Navya Gangrade', 'SCAI CS/E-076 Mayo Clinic - Detecting the toxic in paper review and rewriting them in an encouraging and friendly tone.', 'Some reviews (especially those low score reviews) can be very discouraging (negative), which can lead to unintentional psychological damage (e.g. anxiety or depression) to the authors. Our goal here is to identify the toxicity in the initial paper review and edit the review which still maintains the feedback and suggestions of the initial review but written in a friendly and courageous tone.', 'Imon Banerjee, Man Luo', 5, 'Navya Gangrade, Ariadne Dimarogona, Hari Ramalingame, Rafael Gan, Brad Peterson', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/CDpQw8C6AJI', 'https://youtu.be/CDpQw8C6AJI', '2024-04-14', 'YES'),
(32, 'mlfrazer@asu.edu', 'Mitchell Frazer', 'SCAI CS/E-049 General Dynamics - DevSecOps Audio Playback Application', 'Our project is a full-stack, cloud-based application that allows users to upload, playback and search through historical audio files in the Rescue 21 system. It includes a web application with a GUI, an API that provides audio file metadata & streams of audio to clients, and a MongoDB database to catalog audio files.', 'General Dynamics Mission Systems (Gary Saunders, Paco Jauregui)', 4, 'Mitchell Frazer, Martin Lizarraga, Brandon Winslow, Ethan Hillman, Bilal Elmohandes', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/Cr6a657taGI', 'https://youtu.be/Cr6a657taGI', '2024-04-14', 'NO'),
(33, 'djager2@asu.edu', 'Daniel Jager', 'SCAI CS/E-072 Maasiv Data Visualization', 'Our project was building a front end web application to present data collected by our sponsors internet network monitoring system.', 'Maasiv LLC', 4, 'Daniel Jager, Ian Booth, Kadin Rabo, Liam Engerholm', 'CSE 486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/EnLlPovCXnI', 'https://youtu.be/EnLlPovCXnI', '2024-04-14', 'NO'),
(34, 'rannon@asu.edu', 'Riley Annon', 'SCAI CS/E-107 Relationships & Technology Lab - Sun Devil Dating', 'ASU-exclusive dating app built with Node.js, Python, and React Native to foster student relationships and meanwhile gather data to be used in research for ASU\'s Relationships and Technology Lab.', 'Liesel Sharabi', 5, 'Riley Annon, Yiyang Wang, Fenglin Zhang, Logan Ferrera, Andi Lian', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/oQbwq9zFjYU', 'https://youtu.be/oQbwq9zFjYU', '2024-04-14', 'YES'),
(35, 'wpyeager@asu.edu', 'William Yeager', 'SCAI CS/E-044 Fairmont Scottsdale Princess - Predictive Maintenance and Lifecycle Analysis for Efficient Asset Managem', 'Our project created a predictive maintenance model and life cycle analysis for all operations at the Fairmont Scottsdale Princess resort. The life cycle analysis models all machine replacement and maintenance. This provides the backbone for our predictive maintenance model, which gives a regimented plan to keep operations at the resort running as smooth as possible.', 'Michael Ortiz', 5, 'William Yeager, Kendall Budd, Aria Lilabady, Abdullah Arojojoye, Dikshita Bazarbaruah', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/5Qd_woIcZqA', 'https://www.youtube.com/watch?v=5Qd_woIcZqA', '2024-04-14', 'YES'),
(36, 'kdjarme@asu.edu', 'Kristoffer Nikko Deblois Jarme', 'SCAI CS/E-088 NASA - Web-Based Game for Psyche 12J', 'A web-based game for all ages designed to help inform the public about NASA\'s Psyche mission. After your cows wreak havoc on the nearby psyche launch recreation, your task is to explore nearby planets to collect the lost satellite pieces. Explore 3D levels while learning about the components of the satellite that is being sent to investigate Psyche!', 'Cassie Bowman', 4, 'Brian Cole, Dadmehr Safara, Maria De Jesus Rizo, Kristoffer Nikko Deblois Jarme', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/3nYSN9N2pJ8', 'https://youtu.be/3nYSN9N2pJ8', '2024-04-14', 'YES'),
(37, 'hdobos@asu.edu', 'Orion Dobos', 'SCAI CS/E-078 Meteor Studio at ASU - Haptic Media Controller for Virtual Reality in Dreamscape Learn', 'The Haptic Media Controller is a portable control panel designed to enhance user interaction within Dreamscape Learn. This device allows users to control various aspects of their virtual environment right at their fingertips, from animations and video media to programmable environmental changes.', 'Meteor Studio at ASU', 6, 'Richard Callahan, Allen Lin, Aleksandr Cooper, Zachary White, Orion Dobos, Luke Philipps', 'CSE424, CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/f9jvCWmlDso', 'https://youtu.be/f9jvCWmlDso', '2024-04-14', 'YES'),
(38, 'cjrodr17@asu.edu', 'Christopher Rodriguez Diaz', 'SCAI CS/E-070 Local Grown Salads - LGS EcoSystem', 'The project is to design and create mobile applications for different customer types. Our application will enable customers to easily order our products online, track their orders, and receive notifications about new products and promotions. We are committed to providing customers with the freshest, most nutritious, and environmentally sustainable produce possible.', 'Zale Tabakman', 4, 'Christopher Rodriguez Diaz,  Ahmed Alyahya, Duy Vo, Ryan Grimes', 'CSE 486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/PXyhxKj1mJ8', 'https://youtu.be/PXyhxKj1mJ8', '2024-04-14', 'NO'),
(39, 'nbandeme@asu.edu', 'Nathaniel Bandemer', 'SCAI CS/E-077 Mayo Clinic - Development of Generalizable Large Language Model for Repurposing Clinical Notes', 'We developed NLP models that extract social determinants of health from discharge summaries. These SDOHs are often missing from hospital records, and provides valuable insight into the social history of a patient which can be critical for proper care.', 'Mayo Clinic', 5, 'Manav Shah, Mudit Arora, Nathaniel Bandemer, Priyanka Tadepalli, Tiffany Ticlo', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/3c5PrFX6wBQ', 'https://youtu.be/3c5PrFX6wBQ', '2024-04-14', 'YES'),
(40, 'kdvilla3@asu.edu', 'Kyle Villa', 'SCAI CS/E-002 3D Print Lab Ticketing System', 'A database hosted on Docker that manages the 3D prints for the ASU 3D print lab. The database is accessed using c# and two react.js websites for the frontend.', 'Justin Herring', 5, 'Kyle Villa, Asher Baptista, Nicholas Shaw, Cameron Sharp, Joshua Inman', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/cQlpt0sxnvY', 'https://www.youtube.com/watch?v=cQlpt0sxnvY', '2024-04-14', 'YES'),
(41, 'alimaye2@asu.edu', 'Aparajita Limaye', 'SCAI CS/E-102 Play Forever - Return Pal  - Return Pal App', 'Return Pal is a return service and a social enterprise for Play Forever, which is dedicated to providing structured and accessible recreation, education, and mental health services to youth. We are looking to develop an app for both iOS and Google Store platforms. The app should include features such as user sign-up (e.g., Google login), online scheduling (pick up date and address), payment processing, and shipping information from the sender.', 'Hasan-Ali Abidi', 5, 'Nguyen Nguyen, Eric Gomez-Flores, Hassan Alkaabi, Charmi Patel, Aparajita Limaye', 'CSE 486 and CSE 424', 'No', 'No', 'No', 'https://www.youtube.com/embed/LHmr-6L2oLA', 'https://youtu.be/LHmr-6L2oLA', '2024-04-14', 'YES'),
(42, 'agandava@asu.edu', 'Abhisekhar Bharadwaj Gandavarapu', '23F-028 Psyche 2 - Web-Based Game for Psyche', 'Asteroid Tycoon is our NASA-sponsored web game that aims to deliver an immersive and educational experience, fostering excitement for space exploration and highlighting the NASA Psyche mission. Players engage in strategic resource extraction within an asteroid system, progressing through a tech tree, exploring caves, and deploying satellites to uncover hidden resources. Grounded in reality, this game offers a formal platform for understanding future space missions while promoting scientific curiosity and learning.', 'NASA Psyche Mission', 4, 'Adrian Mena Altamirano, Abhisekhar Bharadwaj Gandavarapu, Justin Lavi, Joesph Dunagan', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/FL7AsPCRMEQ', 'https://www.youtube.com/watch?v=FL7AsPCRMEQ', '2024-04-14', 'NO'),
(43, 'rhhu1@asu.edu', 'Ray Hu', 'SCAI CS/E-064 Inhance Digital Corporation - Development of Virtual and Mixed Reality Platform for Managing Large-Scale Operations', 'An Unity application SDK to allow developers to quickly generate and use map game objects in world-space. This project utilizes Microsoft\'s Mixed Reality tools and the Google Maps API to allows users to update and manipulate virtual maps in the real world.', 'Inhance Digital', 2, 'Ray Hu, Atharva Dhoke', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/wOUJgqSsutk', 'https://www.youtube.com/watch?v=wOUJgqSsutk', '2024-04-14', 'NO'),
(44, 'malghufa@asu.edu', 'Mohammed Alghufaili', 'SCAI CS/E-046 Fourcher Technologies - Senior Tech Support AI', 'In a world increasingly driven by technology, the Fourcher Technologies Senior Tech Support AI project seeks to address the unique challenges faced by seniors in navigating the digital landscape. The primary purpose of this project is to empower seniors with a tool that simplifies their interaction with technology. By providing tailored assistance, our AI solution aims to assist seniors in overcoming hurdles such as troubleshooting issues, navigating the internet, and accessing information effectively.', 'Jordan Fourcher - jordanfourcher@fourchertech.com', 4, 'Aditi Rai, Asra Mohiuddin, Mohammed AlghufailI, Trey Schmieder', 'CSE424, CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/Ugmp3QvsRmw', 'https://youtu.be/Ugmp3QvsRmw', '2024-04-14', 'YES'),
(45, 'jpurice@asu.edu', 'Jesse Purice', 'SCAI CS/E-017 ASU - Dynamic Traffic Dataset Creation for VIPLE Traffic Simulator Machine Learning', 'Our project set out to create realistic traffic conditions inside of the VIPLE traffic simulator with dynamic routing. This requires gathering realistic data, creating a machine learning model, and injecting the traffic data into the simulator for the Dijkstra\'s algorithm calculations.', 'Yinong Chen, Gennaro De Luca', 4, 'Andrew Gantner, Zakery Collins, Ahnaf Chowdhury, Jesse Purice', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/Z6T6gHmfO4I', 'https://youtu.be/Z6T6gHmfO4I', '2024-04-14', 'YES'),
(46, 'athudso1@asu.edu', 'Andrew Hudson', 'SCAI CS/E-036 DigiClips - DigiClips Media Search Engine', 'Digiclips is a multimedia search engine that lets you search social media, newspapers, magazines etc. simultaneously. Along with providing analytics, Digiclips aims to provide a complete picture of results for a particular query through use of multiple sources as mentioned above. Digiclips also provides email alerts for subscribers that constantly keep you updated on important queries.', 'Bob Shapiro, Henry Bremers', 4, 'Andrew Hudson, Daniel Burgin, Jerrian Tocmo, Minh Khang Nguyen', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/WtONaZv4goc', 'https://youtu.be/WtONaZv4goc', '2024-04-14', 'YES'),
(47, 'byang64@asu.edu', 'Branden Yang', 'SCAI CS/E-021 ASU SCAI - Deterministic Fuzzing Replay and Debugging', 'Fuzzing is an innovative method of finding bugs and vulnerabilities in a program, which involves using a high amount of randomness to modify and mutate program inputs. As a result, fuzzing is more of an art than a science. In order to make the development of fuzzing more structured and procedural, this project aims to introduce a framework which can inject itself into a fuzzer so that the necessary metadata for replaying a fuzz run is collected and can be replayed.', 'Dr. Tiffany Bao', 2, 'Denis Liu, Branden Yang', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/lXdofJQ9fa0', 'https://youtu.be/lXdofJQ9fa0', '2024-04-14', 'YES'),
(48, 'anahar1@asu.edu', 'Anish Nahar', 'SCAI CS/E-056 Honeywell Aerospace - Building a Vision based perception layer to enable autonomous operations', 'Development of a vision-based system that can track the movement of objects in a scene and display the output of the model using a user-friendly and accessible UI.', 'Nayyar Rao', 5, 'Jonah Reese, Jack Cruz, Anish Nahar, Daniel Tjandra, Zachary Snider', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/apBCc2uDQgs', 'https://youtu.be/apBCc2uDQgs', '2024-04-14', 'YES'),
(49, 'cwkim3@asu.edu', 'Christopher Kim', 'SCAI CS/E-097 Personal Project - Threat Awareness System Project', 'The Threat Awareness Project is a model designed to detect car objects and provide notifications to pedestrians via an app, indicating whether it\'s safe to cross crosswalks. The video showcases the model in action, demonstrating its detection capabilities and the feedback provided through the application.', 'John Lewis', 5, 'Dac Le, Justin Young, Christopher Kim, Saad Kadhi, Luna Stephenson', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/v3kIPrqDxSY', 'https://www.youtube.com/watch?v=v3kIPrqDxSY', '2024-04-15', 'YES'),
(50, 'agauta20@asu.edu', 'Ayan Gautam', 'SCAI CS/E-018 ASU Judging Capstone Group', 'This project involved creating a Judging application for ASU, which helps in Event Management. Using the app a person can host events, add participants and groups to it, customize grading criterias and invite Judges to score the projects. It proves to be a one stop solution for hosting Events.', 'Steven Osburn', 8, 'Ayan Gautam, Medhansh Garg, Shashank Buddhdev, Sashrik Rajesh, Rajeev Vemuri, Marisa Slepack, Jereane Cachola, William Latus', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/Vkx2gAa4m10', 'https://www.youtube.com/watch?v=Vkx2gAa4m10', '2024-04-15', 'YES'),
(51, 'sgomez47@asu.edu', 'Salvador Gomez', 'SCAI CS/E-040 Eean Bradley Development Studio - WorldME.TV', 'Developed an app “JudyAI” that combines all Judy\'s applications into one easy-to-use platform. Creating a “Chatbot” for Judy to help user with specific needs as well as a “Healthcare App” that can search doctors and able to make appointments with them using flutter and dart. Finally the WorldMe.tv website and the implementation of a live-stream service.', 'Eean Bradley Development Studio', 5, 'Shubhay Dharidharka, Max Droge, Salvador Gomez, Abdulelah Bin Morebah, Abdullah Alsenydi', 'CSE486 and CSE424', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/dTXzL9pf6lo', 'https://youtu.be/dTXzL9pf6lo', '2024-04-15', 'NO'),
(52, 'dkoplik@asu.edu', 'David Koplik', 'SCAI CS/E-032 CoMint - CoMint', 'A peer-to-peer money lending platform that expands access to people regardless of their credit score, letting users negotiate among each other and loan money based on their risk tolerance.', 'Matthew Zomorodi', 5, 'David Koplik, Shubh Vivek Khandelwal, Bao Huynh, Nicholas Gantt, Al-Harith Al-Maawali', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/5pquZC3S0io', 'https://youtu.be/5pquZC3S0io', '2024-04-15', 'NO'),
(53, 'odieterl@asu.edu', 'Owin Dieterle', 'SCAI CS/E-003 Adaptive Concepts LLC - Tri-Sensory Pattern Language (TSPL) for Non-Speaking Persons', 'The purpose of the Tri-Sensory Pattern Language (TSPL) project is to enable communication between a speaking person and non-speaking special needs person. The user is able to input English words which are then converted to TSPL and played back to the user as musical notes. The TSPL program can also take MIDI keyboard input, which is then translated into English and read back to the user.', 'Dave Clark, P.E., President - Adaptive Concepts, LLC', 5, 'Trenton Ward, Owin Dieterle, Chun Ting Ho, Taylor Ferrell, Sabien Najim', 'CSE 424, CSE 485', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/021xtTmuB0o', 'https://youtu.be/021xtTmuB0o', '2024-04-15', 'NO'),
(54, 'tprice14@asu.edu', 'Trevor Price', 'SCAI CS/E-109 Simwerx - VitalSync: Medical Modeling,Simulation & Training', 'Simwerx is building Medic Copilot: A decision support & logistical guidance system for pre-hospital multi-casualty care.  This Dockerized microservice is a part of that effort as it will generate casualty scenario variants, run them through physiology engines that output simulated patient telemetry, and store all the data produced in a data lake for future processing.  Ultimately, the casualty scenario simulation database will enable Machine Learning research and development efforts to train a variety of models', 'SimWerx', 2, 'Trevor Price, Charles Tripp', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/ZDhJWjFhfeo', 'https://www.youtube.com/watch?v=ZDhJWjFhfeo', '2024-04-15', 'YES'),
(55, 'kmmart47@asu.edu', 'Kaitlyn Marie Martinez', 'SCAI CS/E-067 Ira Fulton Schools of Engineering - AI and IoT integration product design', 'BugEyes is an internet of things insect hotel that houses, tracks, and informs consumers about the threatened Monarch butterfly species.', 'Ayca Tuzmen', 3, 'Kaitlyn Martinez , Eathan Ong, and Spencer Ozgur', 'CSE 486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/yioIqyk_jDo', 'https://youtu.be/yioIqyk_jDo', '2024-04-15', 'YES'),
(56, 'jolakken@asu.edu', 'Joseph Olakkengil', 'SCAI CS/E-009 Arrow Electronics Engineering - Automated Label printing application', 'Arrow Electronics tasked us with reviewing their label printing process and designing a website to automate their label printing. The printing website we created is our final deliverable to Arrow.', 'Ethan Berglund/Bill Pinnicks', 4, 'Jacob Clemente, Ricky Das, Andrew Klitsch, Joseph Olakkengil', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/yWh4PTV9roc?si=h08_PQoCa8zlmcJu', 'https://youtu.be/yWh4PTV9roc?si=h08_PQoCa8zlmcJu', '2024-04-15', 'YES'),
(57, 'pnolast9@asu.edu', 'Pratham Gupta', 'SCAI CS/E-086 NASA - Web-Based Game for Psyche 12G', 'Astro Academy aims to ignite a passion for science and space in young learners.​​ It is an interactive web game where the player embarks on a journey to Psyche​​ using animated cutscenes, challenging navigation, and educational quizzes.', 'NASA Psyche Mission', 6, 'Neha Balamurugan, Julie Kye, Leo-Paul Morel, Garrett Goodwin, Pratham Gupta, Maiya Shefik', 'CSE486, IEE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/VOm5kTccRA0', 'https://youtu.be/VOm5kTccRA0', '2024-04-15', 'YES'),
(58, 'spancha5@asu.edu', 'Satvik Panchal', 'SCAI CS/E-015 Astro seed - GreenVision AI: Illuminating the Signs of Nutrient Deficiency and Diseases in Plants', 'This project involves developing a machine learning model designed to analyze images of Lettuce plants and assess their health. Our model accurately identifies various conditions, including six diseases and three nutrient deficiencies, achieving an impressive accuracy rate of 98.53%.', 'Vishnu Bhargav Muthyala', 5, 'Drew Christner, Satvik Panchal, Aidan Simkins, Nathan Cluff, Samarth Dev', 'CSE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/tXpQjePIlZ8', 'https://www.youtube.com/watch?v=tXpQjePIlZ8&feature=youtu.be', '2024-04-15', 'YES'),
(59, 'ewcochr1@asu.edu', 'Erik Cochran', 'SCAI CS/E-047 Fourcher Technologies LLC - Dementia and Alzheimers Digital Product', 'Our team has created a virtual reality simulation of the visual symptoms caused by Alzheimer\'s. The goal of our simulation is to create empathy for those who suffer from this disease.', 'Jordan Fourcher', 5, 'Tyler Allison, Erik Cochran, Sam Cool, Abdurazak Mahamoud, Anthony Rodi', 'CSE424, CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/gJu65YSG0BI', 'https://youtu.be/gJu65YSG0BI', '2024-04-15', 'YES'),
(60, 'rthan@asu.edu', 'Riley Than', 'SCAI CS/E-029 Building Black Youth Foundation - BBYF Learning Management System Research and Development Project.', 'This project details the creation of our Learning Management System demo for Building Black Youth Foundation.', 'Building Black Youth Foundation', 5, 'Riley Than, Jonathan Crammer, Casey Johnson, Matthew DeGard, Sean Dailey', 'CSE 486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/uuVZLR8Chdk', 'https://youtu.be/uuVZLR8Chdk', '2024-04-15', 'NO'),
(61, 'pmontoy2@asu.edu', 'Paul Montoya', 'SCAI CS/E-081 Myself - Legal / Contract Text Aggregator', 'Legal Text Aggegator is an application designed to help with the legal understanding of federal bills and amendments. It can apply amendments from the senate or house to already existing legislation, and provide an easy to read summary of the contents of the bill with the applied amendment.', 'Eric Trant eric.trant@gmail.com', 4, 'Paul Montoya, Bryant Ho, Nicholas Paulette, Avi Arora', 'CSE 424', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/DZvb-cvG8Jk', 'https://www.youtube.com/watch?v=DZvb-cvG8Jk', '2024-04-15', 'NO'),
(62, 'tkwon4@asu.edu', 'Taehoon Kwon', 'SCAI CS/E-112 Technologies Aim Colours Inc.  - Mobile App for IoT Devices', 'General application for Technologies Aim Colours Inc. for their digital fingernail technology. Covers the major aspects requested by the sponsor such as a marketplace page, image upload page, and image design page.', 'Allie Huerta', 5, 'Aissatou Camara, Cooper Heisler, Justin Carter, Taehoon Kwon, Thien Nguyen', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/gyyS-VRbaUg', 'https://youtu.be/gyyS-VRbaUg', '2024-04-15', 'NO'),
(63, 'sshar195@asu.edu', 'Sahil Sharma', 'SCAI CS/E-027 Benchmarking of adaptive quantum algorithms', 'Our project had two major parts, a) Run experimental variations on a quantum adaptive algorithm to determine which variation is the most efficient and b) create a streamlined tool where users can directly edit hyper-parameters to test their own variations of quantum algorithms.', 'Christian Arenz', 2, 'Ariq Haqq, Sahil Sharma', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/YgqG5haOyo4', 'https://youtu.be/YgqG5haOyo4', '2024-04-15', 'YES'),
(64, 'rwarrie2@asu.edu', 'Raghav Warrier', 'SCAI CS/E-025 Avnet Velocity - Natural Language Processing for Data Visualization', 'The purpose of this project is to create a natural language powered data visualization application that allows Avnet\'s customers to input simple English queries to visualize their data. Users will be able to submit English queries for data and select a graph type, which will then be plotted onto the screen.', 'Xian Zheng and Henry Zhao, Avnet Velocity', 5, 'Woojeh Chung, Shankar Kailas, Ninad Tashildar, Nidhi Thakkar, Raghav Warrier', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/L4H87eh_3_g', 'https://www.youtube.com/watch?v=L4H87eh_3_g', '2024-04-15', 'NO'),
(65, 'kevinle3@asu.edu', 'Kevin Le', 'SCAI CS/E-048 GDMS - Web-based Asset Tracking Tool', 'Our project was to create a tool that is easy to use with all the functionality necessary for asset management. This tool integrates a relational database with a user-friendly interface, enabling seamless tracking and management of assets. Its customization options and user profiles promise to enhance team organization and productivity.', 'Joe Mooney and Timothy Planalp - General Dynamics Mission Systems', 5, 'Kevin Le, Stephen Austria, Zoe Alinea, Miles Koehnemann', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/sjMOKHge85E', 'https://youtu.be/sjMOKHge85E', '2024-04-15', 'YES'),
(66, 'sgarg53@asu.edu', 'Sahil Garg', 'SCAI CS/E-063 Inhance Digital Corporation - Development of Virtual and Mixed Reality (VR/MR) Platform for Healthcare and Emergency Medicine Education', 'The project goal was to create an XR annotation system as a Unity package. This will allow the sponsor to add the Unity Package to any future project to add the annotation feature. This includes being able to create, manipulate, and save drawings in the 2D and 3D space.', 'Inhance Digital', 4, 'Sahil Garg, Mario Garcia, Nicolas Ordonez, Matthew Corey', 'CSE 486, CSE 424', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/p3zGqv5aaMw', 'https://www.youtube.com/watch?v=p3zGqv5aaMw', '2024-04-15', 'NO'),
(67, 'bstokman@asu.edu', 'Benjamin Stokman', 'SCAI CS/E-111 Technologies AIM Colours Inc.  - Mobile app & programming for NFC-controlled wearables', 'Our project was to create and implement a backend system for a future mobile app which will manage pattern changing wearable fingernails. We designed the foundation for our system with the final product, and what would best suit it in mind. We went through many iterations and re-designs.', 'Allie, contact@aimcolours.com', 5, 'Ben Stokman, Daphney Rubio, Isaiah Rhymes, Kushal Paliwal, Mason Cooper', 'CSE424, CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/kAITzM7oP8M', 'https://www.youtube.com/watch?v=kAITzM7oP8M', '2024-04-15', 'NO'),
(68, 'mrnavar2@asu.edu', 'Manuel Navarro', 'SCAI CS/E-041 Etherea - Social Impact App Development Project', 'Etherea is a social app where users tackle missions on personal and global topics, earning points and competing with friends. It allows users to make an everyday difference and track how much you have done. Etherea empowers users to make a positive impact while connecting with others.', 'Celina Mankarios (celina.mankarios@gmail.com)', 5, 'Axcel Lopez, Harish Rattu, Kawthar Alabduljabbar, Manuel Navarro, Prakhar Ghirnikar', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/_g1RdiAsvE0', 'https://youtu.be/_g1RdiAsvE0', '2024-04-15', 'NO'),
(69, 'scpatel7@asu.edu', 'Sheil Patel', 'SCAI CS/E-005 AiTunes Recommender', 'Our software takes in a user inputted song name and artist and outputs a song that the system thinks is a similar or related song to the one that was inputted.', 'Adam Awale', 3, 'Sheil Patel, Alejandro Briones, Christopher Kontsis', 'CSE424', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/r_hh8j4YlC8', 'https://youtu.be/r_hh8j4YlC8', '2024-04-15', 'YES'),
(70, 'bcpete10@asu.edu', 'Bryan Peterson', 'SCAI CS/E-100 Planet Fintech - Planet Fintech', 'Planet Fintech/Fintech411 is a website focused on capitalizing on the booming Fintech industry by creating an easy to use job board solely on fintech.', 'Peter Yassopoulos, Laura Prendergast', 3, 'Bryan Peterson, Jose Loya contreras, Shourya Srivastava', 'CSE486, CSE 424', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/67cfcTTRCIo', 'https://www.youtube.com/watch?v=67cfcTTRCIo', '2024-04-15', 'YES'),
(71, 'ichmelni@asu.edu', 'Ilan Chmelnik', '23F-016 Bristol Myers Squibb - Downtime Tracking and Analysis', 'The Capstone project involved developing and implementing an Excel-based downtime tracker for Bristol Myers Squibb, a leading biopharmaceutical company. This tool aimed to provide comprehensive visualizations of long-term downtime data within the plant to enhance decision-making processes at BMS.', 'Bristol Myers Squibb', 3, 'Ilan Chmelnik, Jorge Frausto, Alabbas Al Harthi', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/g0es-ep0Drw', 'https://youtu.be/g0es-ep0Drw', '2024-04-15', 'YES'),
(72, 'agguti12@asu.edu', 'Ariel Gutierrez', 'SCAI CS/E-039 DreamScape One Inc - Interactive Communication Portal for mobile users', 'The interactive communication portal aims to link businesses and users together with a simple chat interface.  Users and businesses will be able to have real-time feedback when they send each other messages.  A website and mobile application were developed for this project.', 'Anthony Panchoo', 5, 'Ghaida Almalki, Ariel Gutierrez, Henry Reed, Nikita Salikov, Jennifer Yan', 'CSE486, CSE424', 'No', 'No', 'No', 'https://www.youtube.com/embed/BmqIpaKmm34', 'https://www.youtube.com/watch?v=BmqIpaKmm34', '2024-04-15', 'YES'),
(73, 'juribe5@asu.edu', 'Joaquin Uribe', 'SCAI CS/E-087 NASA - Web-Based Game for Psyche 12H', 'A NASA Web Based Game called \"Galactic Capitalist\", that engages the user with a clicker style game that unlocks \"classified\" information about the Psyche Mission. The game educates the player about the mission ranging from facts of the spacecraft to the metallic asteroid.', 'Cassie Bowman', 5, 'Joaquin Uribe, Amanda Holt, Phil Terrani, Parth Rawat, Saadhana Srikar', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/yX36JzIQh_4', 'https://youtu.be/yX36JzIQh_4', '2024-04-15', 'YES'),
(74, 'rwilangk@asu.edu', 'Rayhan Wilangkara', 'SCAI CS/E-007 Anemoia Studios - Streaming Service', 'Our team built a streaming platform using the MERN stack. On the client side we are using React hosted with Vercel. This architecture ensures smooth interaction between the client and Node server, which is built on Express and supported by a Mongo NoSQL database for efficient data handling.', 'Bej’a A. Christmas, beja@anemoiastudios.com', 5, 'Alexander Nguyen, Blaise Harper, Isaac Paschall, Javier Aguilar, Rayhan Wilangkara', 'CSE486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/ot8oZJzwcp4', 'https://www.youtube.com/watch?v=ot8oZJzwcp4', '2024-04-15', 'YES'),
(75, 'jsgarc12@asu.edu', 'Juan Garcia', 'SCAI CS/E-074 MarTek, Inc. - Wafer Prober Calibration System & Mobile App', 'We have been designing and building an improved calibration system that measures and automatically corrects stepping inaccuracies across the prober wafer processing area. The system uses both internal cameras and an external camera and measurement tools to calculate the stepping accuracy. The new system is designed to significantly improve manufacturing flows and processing time by reducing the amount of time it takes to generate the files required to make sure the stepping accuracy is within specifications.', 'Stephen Rains, stever@martekprober.com', 5, 'Wade Liddicoat, Juan Garcia, Basim Elbayar, Kyle Gilman, Noah Ivicic', 'CSE486, CSE424', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/inOiMm1Rwbg', 'https://www.youtube.com/watch?v=inOiMm1Rwbg', '2024-04-15', 'NO'),
(76, 'tvtruon1@asu.edu', 'Taman Truong', 'SCAI CS/E-062 In-home IoT Hub with companion mobile application', 'In this project, we designed and developed a comprehensive home automation system that centralizes control, synchronizes audio, enhances privacy, enables voice-activated commands, and provides tailored automation recommendations to optimize daily living experiences. Using open-source resources and a Raspberry Pi, we were able to create a cheap, yet robust and improved, version of an internet-of-things (IoT) hub with a companion mobile application to power our functionalities. Our interactive graphical user interface and mobile application allows users to operate the hub both at home and on the go!', 'Dr. Soumya Indela', 5, 'Ethan Hubbard, Rini Jain, Anant Rastogi, Carson Streiff, Taman Truong', 'Ethan Hubbard (CSE 424), Rini Jain (CSE 486), Anant Rastogi (CSE 424), Carson Streiff (CSE 424), Taman Truong (CSE 424)', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/Yn_iZl9v9z0', 'https://youtu.be/Yn_iZl9v9z0', '2024-04-15', 'YES');
INSERT INTO `ShowcaseEntries` (`EntryID`, `Email`, `Name`, `ProjectTitle`, `ProjectDescription`, `Sponsor`, `NumberOfMembers`, `MemberNames`, `CourseNumber`, `Demo`, `Power`, `NDA`, `VideoLink`, `VideoLinkRaw`, `DateStamp`, `ShouldDisplay`) VALUES
(77, 'rnucuta@asu.edu', 'Raymond Nucuta', 'SCAI CS/E-065 Intelligent Mobility - &BOUNDS Scalability and AI Embellishment', 'To improve the scalability of &Bounds/Intelligent Mobility\'s insole manufacturing infrastructure, the team adopted a three-fold approach. The monolithic application was segmented into distinct microservices using the strangler pattern, and the iOS application received a revamp and integration with Shopify to enhance user experience. Additionally, advanced machine learning techniques automated the insole generation process.', 'Jeshua Joseph', 5, 'Anirudh Ramasubramanian, Dhruv Samdani, Justin Jin, Raymond Nucuta, Austin Wright', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/erFx4PCaImQ', 'https://www.youtube.com/watch?v=erFx4PCaImQ', '2024-04-15', 'NO'),
(78, 'saliu1@asu.edu', 'Simon Liu', 'SCAI CS/E-031 Capstone Submission', 'This project is a full-stack web application for ASU capstone capstone proposal submissions. The original website uses Google Sites and Google Sheets, which makes it difficult to run scripts on. We created this web application to solve this issue, utilizing React and Laravel for front-end and back-end and a MySQL database to store all submissions.', 'Steven Osburn', 2, 'Simon Liu, Wael Krdi', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/M6PVstwFcHk', 'https://youtu.be/M6PVstwFcHk', '2024-04-15', 'YES'),
(79, 'gccooper@asu.edu', 'Genevieve Cooper', 'SCAI CS/E-038 DORA', 'DORA is a Deployable Optical Receiver Array Cubesat created by ASU students, JPL, NASA and several other industry partners. The purpose of DORA is to increase connections of Spacecrafts by using a SWARMing method to communicate. Using HAM Radio and Optical Transceivers, DORA reduces the Deep Space Network load of other Satellites and itself.', 'Dr. Danny Jacobs', 2, 'Genevieve Cooper, Ryan Skabelund', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/BJzR51Ofm8k', 'https://youtu.be/BJzR51Ofm8k', '2024-04-15', 'YES'),
(80, 'tdong10@asu.edu', 'Tianyu(Bruce) Dong', 'SCAI CS/E-096 Performance Software - Airport Mapping Maintenance Automation', 'The project aims to develop an automated chart comparison system to enhance the efficiency and accuracy of an existing PDF Comparison Utility. The current chart comparison process is time-consuming and requires supervision, leading to potential errors and inefficiencies. The proposed solution involves leveraging AI techniques to automate and optimize the chart comparison process and reporting, reducing manual effort and improving overall chart management.', 'Michael Karalewich & Chris Ihling', 5, 'Tianyu Dong, Brent Conrad Soliman, Nathan Jayanthan, Vincent Ortiz, Bhargav Chirravuri', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/6nUTtY6XfYs', 'https://www.youtube.com/watch?v=6nUTtY6XfYs', '2024-04-15', 'YES'),
(81, 'lltran@asu.edu', 'Leon Tran', 'SCAI CS/E-033 Coy Creator - Manual Software Testing', 'Manual end-to-end regression testing for in-development web software, followed by the creation of automatic testing scripts using the automation library Playwright. These automatic tests allow developers to verify whether their web software is functioning normally or identify where a problem in the software might be.', 'Patrick Teng', 3, 'Javier Garcia, Marc Sagario, Leon Tran', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/dpdz7UWq7rE', 'https://youtu.be/dpdz7UWq7rE', '2024-04-15', 'YES'),
(82, 'vraviku3@asu.edu', 'Varun Ravi Kumar', 'SCAI CS/E-006 Amazon Web Service Explorer', 'Amazon Web Service Explorer enhances the user experience for AWS S3 by providing an intuitive interface where users can preview the contents of their S3 buckets without getting charged retrieval fees. Users have the flexibility to view either their personal buckets or all buckets associated with their organization, facilitating better data management and oversight. Additional features include the ability to delete owned buckets and merge buckets and downloading their data directly from our service, streamlining storage management and optimization.', 'Ramya Rajamani', 3, 'Varun Ravi Kumar, Alexander Rotteveel, James Rausch', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/F1ga_mrxRlU', 'https://www.youtube.com/watch?v=F1ga_mrxRlU', '2024-04-15', 'YES'),
(83, 'aherre55@asu.edu', 'Alejandro Herrera', 'SCAI CS/E-014 Astro Seed - GreenMart: An Online Marketplace', 'Astro Seed - GreenMart Marketplace is an online platform designed to connect local Terra Pod growers with buyers seeking fresh, locally grown produce. By simplifying transactions and promoting sustainable agricultural practices, it addresses the challenges of market access and direct sales in the agriculture sector. This marketplace enhances community engagement and supports healthier, more sustainable eating habits by making local foods more accessible.', 'AstroSeed  Vishnu Bhargav Muthyala', 5, 'Alejandro Herrera, Al Faisal Al-Maawali, Meriam Narouz, Munachimso Aneke, Sasank Chowdary Arekapudi', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/0dR22I-y5A0', 'https://youtu.be/0dR22I-y5A0', '2024-04-15', 'YES'),
(84, 'yxuan4@asu.edu', 'Yongzai Xuan', 'SCAI CS/E-101 Play Forever  - Play Forever App', 'Develop an application inspired by Playforever\'s official website, with an emphasis on a user-friendly GUI and UI design to ensure effortless navigation and engagement. Organize distinct sections dedicated to program details, volunteer opportunities, upcoming events, and donation avenues, facilitating intuitive access to each aspect of the platform.', 'Mohamed Al-Salem Email:mohammed@playforever.ca', 4, 'Yongzai Xuan, Saud Al Kalbani, Dev Malik, Edgar Aquino Barrientos', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/TYQMGiIHfqQ', 'https://www.youtube.com/watch?v=TYQMGiIHfqQ', '2024-04-15', 'YES'),
(85, 'sagarw91@asu.edu', 'Sanket Sandeep Agarwal', 'SCAI CS/E-066 Intelligent Mobility - &BOUNDS Scalability Embellishment (Back-End)', 'Frontend team tackled app issues with specific tech stacks, identified challenges, and strategized solutions effectively.Backend team overhauled monolithic node.js backend to highly scalable microservices also leveraging a CI/CD pipeline to create an efficient pipeline for proper deployment.', 'Jeshua Ben Joseph', 6, 'Sanket Sandeep Agarwal, Anthony Bibbo , Krishna Narasimhan, Siddharth Jain, Aryan Gupta, Pal Neema', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/UOlLr2KL8kI', 'https://youtu.be/UOlLr2KL8kI', '2024-04-15', 'NO'),
(86, 'aahuja16@asu.edu', 'Avneet Ahuja', 'SCAI CS/E-084 NASA - Web-Based Game for Psyche 12E', 'A web based game developed in Unity3D to educate people about NASA\'s Psyche Mission.', 'Cassie Bowman', 5, 'Avneet Ahuja, Om Shewale, Curtis Weber, Radhesh Choudhary, Jonny Duong', 'CSE 486, CSE486, CSE424, CSE486, CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/gpWy9nTrshA', 'https://www.youtube.com/watch?v=gpWy9nTrshA', '2024-04-15', 'YES'),
(87, 'cearles@asu.edu', 'Christopher Earles', 'SCAI CS/E-080 Moog Inc - Object Tracking Algorithm Implementation on Low-Power Embedded GPU', 'Develop a program to analyze a video feed to detect empty parking spots and vehicle movement, to be deployed on a low power system.', 'Tyron Rieckmann, Moog Inc.', 5, 'Feras Al-Qassas, Rohan Chandra, Karthik Dubba, Christopher Earles, Nicholas Rocchi', 'CSE486, CSE424', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/ObNylhvgysY', 'https://youtu.be/ObNylhvgysY', '2024-04-15', 'NO'),
(88, 'wliao18@asu.edu', 'Wei-Cheng Liao', 'SCAI CS/E-075 MarTek, Inc. - Wafer Prober Control Software & Mobile App', 'The purpose of this project is to begin the development of a modern codebase to drive and interface with the wafer prober hardware manufactured by Martek Inc. Besides, a mobile user app is developed to control the wafer prober and monitor the numbers from the prober.', 'Stephen Rains', 5, 'Dhairya Modha, Seth Oltmans, Devansh Tomar, Wei-Cheng Liao, Lazo Sedor', 'CSE486, CSE424', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/PgpvqloN9xI', 'https://www.youtube.com/watch?v=PgpvqloN9xI', '2024-04-15', 'NO'),
(89, 'srajeev@asu.edu', 'Sankalp Rajeev', 'SCAI CS/E-010 Astro Seed - Botanical Cyborg: Robotic Arm for Terra Pod\'s Plant Maintenance', 'Robotic Arm for plant care', 'Vishnu Bhargav Muthyala | Astroseed', 5, 'Matthew Domann, Alexander Rusk, Ayham Isaac, Sankalp Rajeev, Victor Duenas', 'CSE 486,CSE 424', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/ZS4f8PoPhBQ', 'https://youtu.be/ZS4f8PoPhBQ', '2024-04-15', 'NO'),
(90, 'jeiselt@asu.edu', 'Jordan Eiselt', 'SCAI CS/E-012 Astro Seed - GreenEye: Autonomous Drones for Plant Health Monitoring and 3D Mapping', 'Our project is automating a drone to navigate through a small greenhouse and placing waypoints at points of interest. The project will be used in conjunction with other Astroseed groups to create a mobile plant monitoring.', 'Vishnu Bhargav', 4, 'Jayson Albizures, Jordan Eiselt, Nicholas Hildebrant, Nicholas Johnson, Dipanshu Singh,', 'CSE 424, CSE 486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/uUM-VWd7ZBw', 'https://youtu.be/uUM-VWd7ZBw', '2024-04-15', 'YES'),
(91, 'jmanila@asu.edu', 'Justin Manila', 'SCAI CS/E-004 AI-Driven NPCs in Video Games', 'Project persona is a service intended for all types of game developers that gives them the ability to create more advanced and personalized non-playable characters within their games. It utilizes the power of OpenAI’s ChatGPT to imitate the personality of a certain character based on the parameters given by the developer themselves. The project itself consists of a fully functional interface where the developer can create and save stories, personas, scenes, and more that can then be utilized into their own games.', 'Justin Selgrad', 4, 'Zachary Habib, Thomas Derr, Nathan Lind', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/QlfHCqfolxs', 'https://youtu.be/QlfHCqfolxs', '2024-04-15', 'YES'),
(92, 'vleong@asu.edu', 'Vincent Leong', 'SCAI CS/E-113 The Big Leaf - KnowQuest Inc.', 'A platform for consumers to find and provide reviews on a variety of products and services. Businesses can also purchase access to these reviews in data format to use for business analytics', 'KnowQuest - The Big Leaf', 5, 'Adam Karman, Vincent Leong, Faisal Aloraini, Faisal Alaklabi, Likhit Yarramsetti', 'CSE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/Qua9GcjTNMU', 'https://youtu.be/Qua9GcjTNMU', '2024-04-15', 'YES'),
(93, 'jswakefi@asu.edu', 'Jackson Wakefield', 'SCAI CS/E-030 Capstone Showcase Projects - ASU', 'We created this website! The site showcases all CS/CSE/IE Capstone projects and students\' work over the last 2 semesters. We also created the survey that students filled out which contains the information in this site and helps ASU professors prepare for the in-person showcase.', 'Arizona State University', 2, 'Jackson Wakefield, Jacob Licko', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/jdzLUWS59wo', 'https://youtu.be/jdzLUWS59wo', '2024-04-15', 'YES'),
(94, 'lewilhe1@asu.edu', 'Lance Wilhelm', 'SCAI CS/E-053 General Dynamics - Vessel STE Replacement', 'We used a drone based platform to work with General Dynamics and the Coast Guard in order to calibrate their rescue towers. Overall, we made a system to calibrate the towers along with an automatic system for being able to post process the data.', 'Jason Landoll', 5, 'Lance Wilhelm, Brandon Fenske, Caelan Desmond, Josh Budd, Maaz Chohan', 'CSE486, CSE424', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/15bqoiM5ga4', 'https://youtu.be/15bqoiM5ga4', '2024-04-15', 'YES'),
(95, 'asangelk@asu.edu', 'Arnav Sangelkar', 'SCAI CS/E-068 Ireland Outfitters', 'Ireland Outfitters is an equipment rental company that provides hiking and camping equipment for people visiting Ireland. To help in this mission, we created a website that allows customers to book rentals online.', 'Colleen Burgess', 3, 'Arnav Sangelkar, Enan Ahmed, Liam Douglas', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/uGe09NzW8J4', 'https://youtu.be/uGe09NzW8J4', '2024-04-15', 'YES'),
(96, 'hcclarke@asu.edu', 'Holden Clarke', 'SCAI CS/E-011 Astro Seed - Green Intelligence: Decode the Correlation between Environmental Parameters and Plant Physical Features', 'Developing a deep learning model to relate environmental parameters to physical plant features', 'Vishnu Bhargav', 5, 'Adi Keshava Reddy Mamilla, Emmanuel Cortes Castaneda, Holden Clarke, Luis Medina, Zackary Guajardo', 'CSE 486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/tk-jm-LKpD0', 'https://www.youtube.com/watch?v=tk-jm-LKpD0', '2024-04-15', 'YES'),
(97, 'rdeb3@asu.edu', 'Roshni Deb', 'SCAI CS/E-059 Humane Futures Lab - Gleo Foundations', 'Gleo is a cutting-edge social media platform that encourages and rewards users for taking part in community-related activities like volunteering and civic engagement. The central feature of the Gleo platform is its point-based reward system, which enables users to accrue and exchange points for different rewards provided by affiliated companies, enhancing community participation and teamwork. This strategy promotes community growth by fostering relationships with nearby businesses and encouraging active participation.', 'Karan Patil', 5, 'Roshni Deb, Justin Kereszturi, Benjamin Jackson, Alondra Contreras, Burhan Barafwala', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/TqHUYzFdRlE', 'https://www.youtube.com/watch?v=TqHUYzFdRlE', '2024-04-15', 'YES'),
(98, 'thirvin@asu.edu', 'Trevor Irvin', 'SCAI CS/E-050 General Dynamics - Hardening Linux OS', 'Our team performed security hardening on a Linux OS for General Dynamics in order to reduce vulnerabilities in an embedded system.', 'General Dynamics Mission Systems', 5, 'Trevor Irvin, Michael Toliver, Mary Nicholson, Austin Harris, Chandler Camarena', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/o3z5-o7MNjE', 'https://youtu.be/o3z5-o7MNjE', '2024-04-15', 'NO'),
(99, 'amhobbs@asu.edu', 'Angelina Hobbs', 'SCAI CS/E-099 Personal Projects - Topic: Object Tacking and Locating', 'The Object Tracking and Locating project develops a computer vision-based system for detecting and tracking animals, suitable for both household pets and wildlife. It uses custom-trained machine learning models to process live and recorded video footage. Key features include annotated footage, a detailed log of animal detections with timestamps, a customizable notification system for live feed detections, and a graph that comprehensively visualizes these detections over time.', 'John Lewis', 4, 'Angelina Hobbs, Lucas Klusty, Luis Molina, Carson Linzbach', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/Gb83zC9SL48', 'https://www.youtube.com/watch?v=Gb83zC9SL48', '2024-04-15', 'YES'),
(100, 'tttran29@asu.edu', 'Teresa Tran', 'SCAI CS/E-024 Avnet Velocity - Interactive Data Visualization Web Application', 'Avnet Velocity Interactive Data Visualization Web Application team\'s objective is to create a web application that will allow Avnet customers to create, customize, and save interactive graphs to visualize multiple datasets from a database. The project\'s purpose is to solve Avnet’s need for an in-house customer analytics portal providing security, control, customization, flexibility, scalability, and improved communication.', 'Avnet: Xian Zheng, Henry Zhao', 5, 'Bushra Karim, Princess Luong, Teresa Tran, Anya Yu, Ivan Zou', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/uFChHuk72JI', 'https://youtu.be/uFChHuk72JI', '2024-04-15', 'NO'),
(101, 'bpham7@asu.edu', 'Benjamin Pham', 'SCAI CS/E-114 Truthkeep - Truthkeep Prototype', 'The goal of our project, \"TruthKeep Prototype,\" is to give high-level politicians, such as State Representatives or higher, a potent tool to manage their online reputation and stop potentially damaging information from spreading quickly, which could harm their campaigns and public image. The project\'s potential worth to our clients resides in its capacity to arm them with in-the-moment perceptions of web content, sentiment analysis, and pertinent information pertaining to their public image.', 'William Xander', 4, 'Benjamin Pham, Jared Guthrie, Sparsh Bansal, Aashritha Machiraju', 'CSE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/GwRr6RBgQXg&ab_channel', 'https://www.youtube.com/watch?v=GwRr6RBgQXg&ab_channel=JaredGuthrie', '2024-04-15', 'NO'),
(102, 'gyadlapa@asu.edu', 'Geethika Yadlapati', 'SCAI CS/E-034 Devils\' Den', 'Discover your perfect roommate with Devils\' Den! This innovative app for students simplifies the search by using a matching algorithm to connect you with like-minded peers, equipped with ASU authentication for extra safety and exclusivity. Instant messaging makes communication a breeze, ensuring you find your ideal roomie effortlessly!', 'Adam Awale', 5, 'Geethika Yadlapati, Salih Arman Gundogan, Weed Batarfi, Olivia Eppert, Aarya Mathreja', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/k88ao9C57d8', 'https://youtu.be/k88ao9C57d8', '2024-04-15', 'YES'),
(103, 'agarg67@asu.edu', 'Ananya Garg', 'SCAI CS/E-098 Personal Project - Topic: Non-traditional Communications Channels', 'The Non-Traditional Communication Channels aims to develop an innovative communication method characterized by its anonymity and currently available security between two active clients. To meet our projects requirements, we conducted rigorous research on existing secure communication channels to conceptualize our own novel network architecture. The entire system was then implemented in Python, utilizing a combination of cryptographic algorithms to ensure confidentiality, message integrity and client anonymity within the created communication channel.', 'John Lewis', 5, 'Alexandr Zincenko, Ananya Garg, Eduardo Ortiz Rosas, Harrison Lisk, Nathan Suman', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/YeFub9npG4M', 'https://youtu.be/YeFub9npG4M', '2024-04-15', 'YES'),
(104, 'jaweber7@asu.edu', 'James Weber', 'SCAI CS/E-022 ASU SCAI - Ultrasonic Phased-Array for Mid-Air Haptics', 'Mid-air haptics are tactile sensations you can feel in midair, without needing to come into direct contact with any physical device. Our team developed an ultrasonic phased array which coordinates the phase delays of an array of ultrasonic transducers to create highly pressurized focal points for mid-air haptics. These focal points can shift rapidly in temporal space, allowing varied feedback for enhancing touchless user interaction across diverse mediums.', 'Hasti Seifi', 4, 'James Fink, James Weber, Ben Bloomgren, Blake Anderson', 'CSE486, CSE424', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/awkfbGHzcRU', 'https://youtu.be/awkfbGHzcRU', '2024-04-15', 'YES'),
(105, 'sreza3@asu.edu', 'Sameer Reza', 'SCAI CS/E-060 Hymdal - AI (Fintech) Web-App MVP', 'An MVP data pipeline that takes a list of company websites and analyzes them to find a wide array of relevant information on each company based off of the given schema for later analysis. We couple a scrapy web scraper & an OpenAI integrated information extractor to generate consistent structured JSON data from the fuzzy chaos of the web.', 'Hymdal -  Gustaf Hammarberg', 5, 'Sameer Reza, Nittin Ashok Murugan, Philip Yu, Ryan El-Aawar, Naomi Sano', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/f7u6NXMeX0I', 'https://youtu.be/f7u6NXMeX0I', '2024-04-15', 'YES'),
(106, 'klakers@asu.edu', 'Katherine Akers', 'SCAI CS/E-001 2 Owls Technology - Beatlynk - listen to music in sync with friends and celebrities', '\"BeatLynk\" is an innovative music-sharing platform that seeks to revolutionize the way people connect and engage with their favorite music, friends, and celebrities. Founded by 2 Owls Technology, this project aims to create a new and immersive music experience that is different from the conventional streaming apps. BeatLynk\'s core idea is simple: users can listen to music in perfect synchronization with their friends and celebrities.', 'Lappin Hammond with 2 Owls Technology (lappin@2owls.com)', 5, 'Katherine Akers, Maria Gamino, Rachel Lanier Arozarena, Stephanie Solis, Azam Khan', 'CSE 486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/AUqcEdj9W2Y?si=Vrhg7HhK7s1Hk60j', 'https://youtu.be/AUqcEdj9W2Y?si=Vrhg7HhK7s1Hk60j', '2024-04-15', 'NO'),
(107, 'epark34@asu.edu', 'Ethan Park', 'SCAI CS/E-019 ASU Rideshare App', 'Arizona State University currently lacks a ridesharing app dedicated to its students. Our project is a student-based web application that allows ASU students to arrange rides with one another. The front-end interface was developed using React, while the Express library was utilized for the backend infrastructure.', 'Justin Selgrad', 5, 'Aeric Plitz, Colton Onishi, Ethan Park, Franco De Porzi, and Steven Nguyen', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/QbppYsEBYYI', 'https://youtu.be/QbppYsEBYYI', '2024-04-15', 'YES'),
(108, 'cmhartm4@asu.edu', 'Cameron Hartmann', 'SCAI CS/E-103 Polideck Technologies LLC - Quantum-Resistant Public Key Authentication Server & Client', 'Our project is a server client web application that allows for password less authentication using WebAuthn.', 'Kaitlin Cozzi', 5, 'Harry DeCecco, Cameron Hartmann, Sebastian Rubalcava, Brendan Tith, Aidan Mcclean', 'CSE 486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/JdhwuWtAO4c', 'https://www.youtube.com/watch?v=JdhwuWtAO4c', '2024-04-15', 'NO'),
(109, 'sselvaku@asu.edu', 'Shri Sanjay Kumar Selvakumar', 'SCAI CS/E-071 Lotus Addiction Therapy Inc - Lotus Addiction Therapy Mobile Application Development', 'Lotus Addiction Therapy Inc. offers online/remote addiction and mental health treatment services that are readily accessible. The platform aims to do this by adding new functionalities to the mobile application for iOS and Android and creating a seamless user experience in the website and mobile app. Our contributions focused on improving the platform with new user types, payment plans, and blog pages and resolving bugs that the quality assurance team found.', 'Hamsharan Mahalingam', 5, 'Shri Sanjay Kumar Selvakumar, Robert Ayala, Craig Grande, Alana Gregorio, Ricardo Jardinez Morales', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/BYbMT0nfALc', 'https://youtu.be/BYbMT0nfALc', '2024-04-15', 'NO'),
(110, 'akoyyala@asu.edu', 'Abhinav Koyyalamudi', 'SCAI CS/E-106 Reality Articulated - MurMur: Enhancing Therapy Outcomes', 'Reality Articulated is a revolutionary platform reshaping the therapy landscape by enabling patients to journal their thoughts and emotions directly within the app. These entries are securely shared with therapists, providing valuable insights into patients\' mental states. Through summarized entries and advanced analytics, therapists can offer personalized guidance and deeper understanding during sessions, fostering profound personal growth and healing', 'Karan Patil', 3, 'Spencer Whitefoot, Nash Carlow, Abhinav Koyyalamudi', 'CSE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/X-lULzRkpVY', 'https://youtu.be/X-lULzRkpVY', '2024-04-15', 'YES'),
(111, 'gchallar@asu.edu', 'Greeshma Challaram', 'SCAI CS/E-085 NASA - Web-Based Game for Psyche 12F', 'This capstone project involves developing a web-based game in partnership with NASA. It\'s designed to be a fun and educational tool, helping students learn about NASA\'s recent mission to the asteroid Psyche. The game features a retro 2D style and is being built using the Godot 4 engine.', 'Cassie Bowman (cbowman5@asu.edu)', 5, 'Jack Pletka, Keb Summers, Sukul Handa, Greeshma Challaram, Jonathan Parilla', 'CSE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/eBPbqrQilB0', 'https://youtu.be/eBPbqrQilB0', '2024-04-15', 'YES'),
(112, 'saalkred@asu.edu', 'Saleh Alkredes', 'SCAI CS/E-115 Yanbor LLC - Data Analysis using OUReports technic including matrix balancing', 'OUReports revolutionizes data analysis for organizations with its cutting-edge Online Data Analytics and Reporting capabilities. Its intuitive interface facilitates seamless generation of insightful reports, charts, and dashboards, empowering users to make informed decisions based on data-driven insights. By fostering a data-driven decision-making culture, OUReports enhances organizational efficiency and effectiveness.', 'Irina Yaroshevskaya', 4, 'Faisal Alfawaz, Mazen Alzahrani, Waleed Altamimi, Saleh Alkredes.', 'CSE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/pLa5EhPdPPg', 'https://www.youtube.com/watch?v=pLa5EhPdPPg', '2024-04-15', 'YES'),
(113, 'skancha4@asu.edu', 'Sai Sumant Kancharla', 'SCAI CS/E-089 NASA - Web-Based Game for Psyche 12K', '\"Asteroid Odyssey\" is a captivating 2D trivia game that takes players on an educational journey to the asteroid Psyche, blending space exploration with engaging gameplay.', 'Cassie Bowman', 5, 'Sai Sumant Kancharla, Liam Gomez, Harshavardhana Pratha, John Dibiase, Zain Jakwani', 'CSE486', 'Yes', 'No', 'Yes', 'https://www.youtube.com/embed/_Gor3uiL-fo', 'https://youtu.be/_Gor3uiL-fo', '2024-04-15', 'NO'),
(114, 'bkfische@asu.edu', 'Britton Fischer', 'SCAI CS/E-095 Paqt - Paqt: Create APIs for integration of our web app into partner apps', 'Paqt is an intuitive platform for businesses to manage their agreements with greater ease and efficiency. It lacked any integration with external applications which cut it off from the rest of the internet. We implemented several new features which solve this problem and make their app significantly more competitive.', 'Mike Anderson', 5, 'Britton Fischer, Matthew Rodi, Aidan Labourdette, Brandon Ritchey, Ujjwal Baranwal', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/RcOjAs8tR0g', 'https://www.youtube.com/watch?v=RcOjAs8tR0g', '2024-04-15', 'NO'),
(115, 'kmuraish@asu.edu', 'Aiko Muraishi', 'SCAI CS/E-079 Microbial Metabolism Modeling Lab', 'Our goal in the Microbial Metabolism Modeling project was to improve a computational tool that researchers could employ to simulate networks of microbiological metabolism. The lab\'s ultimate objective is to establish a sustainable manufacturing process by creating a way to produce chemicals from microorganism\'s metabolism efficiently. To that end, we started by designing a MATLAB tool\'s GUI and enhancing its simulation accuracy.', 'Arul Varman (ASU)', 2, 'Nathaniel Alberti, Aiko Muraishi', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/OhOtyslBkOQ', 'https://youtu.be/OhOtyslBkOQ', '2024-04-15', 'YES'),
(116, 'syalama6@asu.edu', 'Siddhartha Yalamanchili', 'SCAI CS/E-023 Automated Hydroponic system', 'Automated Hydroponics System is a project with the goal of creating an inexpensive and simpler alternative to modern hydroponics systems intended for use by a hydroponics hobbyist. Through use of services such as Firebase, Adafruit.io, and Raspberry Pi, we have created a system that takes sensor data and dispalys it in an easy to understand manner for beginners.', 'Ryan Meuth', 2, 'Siddhartha Yalamanchili, Hao Zhen', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/6wFTquOLpyQ', 'https://youtu.be/6wFTquOLpyQ', '2024-04-15', 'YES'),
(117, 'jraiff1@asu.edu', 'Jackson Raiff', '23F-001 Fairmont Princess Resort 1 - Lifecycle Analysis & Predictive Maintenance System', 'The goal of our project was to perform a thorough lifecycle analysis on critical pieces of equipment at the Fairmont Princess Resort. We identified patterns in equipment use and failure rates, setting the groundwork for more informed maintenance strategies. Our goal was to enable the resort to reduce downtime and costs while maintaining a commitment to guest satisfaction.', 'Michael Ortiz', 3, 'Scott Sangmanee, Jackson Raiff, Itzel Aguilar Coconi', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/H8K3i8IPDZc', 'https://youtu.be/H8K3i8IPDZc', '2024-04-15', 'YES'),
(118, 'hgupta31@asu.edu', 'Hriday Gupta', '23F-024 Honeywell Aerospace 1 - Supply Chain Scheduling', 'This Supply Chain Allocation project for Honeywell Aerospace optimizes lead times and profits amid rising product demand. Leveraging Python for data-centric analysis, it establishes a linear programming model and employs Sankey Visualization to streamline allocation processes at the Honeywell site.', 'Honeywell Aerospace', 3, 'Hriday Gupta, Haoyu Wang, Khalid Almattar', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/XlQsb6IQN2w', 'https://youtu.be/XlQsb6IQN2w', '2024-04-15', 'YES'),
(119, 'amholla1@asu.edu', 'Alexis Holland', '23F-008 Los Alamos National Labs 1 - Hazardous Material Transport', 'Our project improved the handling of Transuranic (TRU) waste at Los Alamos National Laboratory by using SIMIO simulation software to model and enhance waste management processes, and developing a digital tool to precisely calculate waste \"Attractiveness Level.\" These innovations significantly increased efficiency and safety in high-level waste disposal, demonstrating that such technological integrations can greatly benefit waste management at federal research facilities.', 'Paul Wilding', 3, 'Alexis Holland, Jacob Staub, Michael Morse', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/Jj6oorOvVnU', 'https://www.youtube.com/watch?v=Jj6oorOvVnU', '2024-04-15', 'YES'),
(120, 'ccouvill@asu.edu', 'Chase Couvillion', '23F-010 Los Alamos National Labs 3 - Operations Regulation Analysis', 'Utilization of AI and machine learning to analyze government regulations and increase operational capabilities', 'Los Alamos National Laboratory', 3, 'Alex Edmiston, Chase Couvillion, Mishelle Arzapalo', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/ShFkg7cjYrs', 'https://youtu.be/ShFkg7cjYrs', '2024-04-16', 'YES'),
(121, 'jparill1@asu.edu', 'Jonathan Parilla', '23F-029 Psyche 3 - Virtual Reality Space Game', 'This capstone project involves developing a web-based game in partnership with NASA. It\'s designed to be a fun and educational tool, helping students learn about NASA\'s recent mission to the asteroid Psyche. The game features a retro 2D style and is being built using the Godot 4 engine.', 'Cassie Bowman', 5, 'Jack Pletka, Jonathan Parilla, Keb Summers, Sukul Handa, Greeshma Challaram', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/Re1JY7wro2A', 'https://youtu.be/Re1JY7wro2A', '2024-04-16', 'YES'),
(122, 'mzoroza@asu.edu', 'Mateo Zoroza', '23F-018 Cryo X - Radiative Cooling Tech', 'Cryo X Co is a startup dedicated to bringing passive daytime radiative cooling technology to the consumer space. Since this tech is so new and innovative, our project required us to take on several experiements in order to learn more about this material\'s properties', 'Cryo X Co', 3, 'Mateo Zoroza, Kylah Coubrough, Vedant Singh Rajput', 'IEE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/l71Gz_6aeEQ?si=5DS42JtvuWGFDX5v', 'https://youtu.be/l71Gz_6aeEQ?si=5DS42JtvuWGFDX5v', '2024-04-16', 'NO'),
(123, 'hkrogers@asu.edu', 'Harold Rogers', '23F-022 Parker Aerospace - Cell transformation of Clean, Check, Test (CCT) cell', 'Parker Hannifin tasked our capstone team with increasing the efficiency of their Clean, Check, and Test value stream by twenty percent and reducing their footprint by twenty percent. With the help of our sponsor and our educational background, we decided to use lean manufacturing methods to achieve these goals and solve problems along the way. Our biggest conclusive deliverables we met were multiple floor layout designs, an updated value stream map, and new process procedures/updates.', 'Parker Hannifin - Eric Fisher', 3, 'Harold Rogers, Jonah Meretsky, James Buckley', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/aehRxPQEwd8', 'https://youtu.be/aehRxPQEwd8', '2024-04-16', 'YES'),
(124, 'jckocsis@asu.edu', 'Jace Kocsis', 'SCAI CS/E-083 NASA - Web-Based Game for Psyche 12D', 'NASA PSyche 12D consisted of the development of an educational web based game, Alloy Explore, that serves to raise awareness of the Psyche mission.', 'NASA', 5, 'Jace Kocsis, Harikrishna Kommineni, Pei-En Pan, Dylan Wynne, Cole Krause', 'IEE 486, CSE 486, CSE 424', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/YynqMlx3OlI', 'https://www.youtube.com/watch?v=YynqMlx3OlI', '2024-04-16', 'YES'),
(125, 'mmferber@asu.edu', 'Marlee Ferber', '23F-005 Innovation Space 1 - Keep Tempe Beautiful: Zero-Waste Music Festival', 'In partnership with ASU’s Innovation Space, working with local non-profit Keep Tempe Beautiful, we are prototyping Zero-Waste ideas for the Tempe City Roots Musical Festival, set to happen in April 2025.', 'Keep Tempe Beautiful', 2, 'Marlee Ferber, Kyle Delasandro', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/HZ_dgQhcLJ4', 'https://youtu.be/HZ_dgQhcLJ4', '2024-04-16', 'YES'),
(126, 'djain31@asu.edu', 'Dev Dinesh Jain', '23F-026 Honeywell Aerospace 3 - Supply Uncertainty', 'This project was introduced to our group as a supply uncertainty problem. This is a value that had to be computed to give an accurate estimate of how certain an order would arrive on the date requested for it to be delivered. The main approach to find this statistic was to code in Python. Then putting the code into a graph format to easily communicate with anyone that could see it useful. The visualization of supply uncertainty works for almost all of the order IDs provided for this project and can be used to forecast and better prepare for uncertainty.', 'Honeywell Aerospace', 2, 'Abdulaziz Alrajhi, Colby Arlington', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/xy7gpidse50', 'https://youtu.be/xy7gpidse50', '2024-04-16', 'YES'),
(127, 'aomendoz@asu.edu', 'America Mendoza', '23F-003 Fairmont Princess Resort 3 - Food Waste Reduction Initiative', 'The Fairmont Princess presents financial and environmental challenges calling for a structured food waste management approach. The luxury resort caters to both banquet events and fine dining, producing a large amount of food waste. The goal of the project was to offer both cost savings and shifts in environmental awareness of food waste.', 'Michael Ortiz', 3, 'America Mendoza, Alexandra Hieber, Saleh Alrajhi', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/Y14FOVlbKkw', 'https://youtu.be/Y14FOVlbKkw', '2024-04-16', 'YES'),
(128, 'tjrowe2@asu.edu', 'Tyler Rowe', '23F-019 Kennedy Space Center - NASA KPD-P-2713 Digital Transformation', 'Sponsored by Jacobs Technology out of Kennedy Space Center as part of the NASA COMET Contract and Artemis Program. Transitioning the document based design review process, KDP-P-2713, into an MBSE style model using MagicDraw SysML and Velocity Templating Language. Enhancing efficiency and quality through document update automation, system requirement interconnection and enhanced knowledge capture of system experts.', 'Jacobs Tech, Kennedy Space Center, NASA', 3, 'William Bustraan, Logan Enyeart, Tyler Rowe', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/YHII7ElYrjc', 'https://youtu.be/YHII7ElYrjc', '2024-04-16', 'YES'),
(129, 'trthornt@asu.edu', 'Tyler Thornton', '23F-020 Prime Solutions Group - Remote Sensing Systems', 'The senior capstone design team was partnered with organization  Prime Solution Group to work on the project, “Lighting Imaging System (LIS) Model using a Digital Engineering Model-based System Engineering (DEMSE)”.  The project required the students to develop a framework for a simulation model of a Neuromorphic camera within the cloud based program Innoslate that would eventually be imported to a PSG server for final integration of a digital twin. The capstone team was also expected to develop System and digital engineering techniques as the project progressed.', 'Prime Solutions Group', 3, 'Stephanie Heim, Oguz Kenes, Tyler Thornton', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/3G_6M5AMZWQ', 'https://youtu.be/3G_6M5AMZWQ', '2024-04-16', 'YES'),
(130, 'kdiazagu@asu.edu', 'Karla Jailine Diaz Aguilar', '23F-014 ASU Health Solutions - Movement Screening for Athletes', 'The Sun Devils Women\'s Volleyball team utilizes an athletic movement screening system, Valor by Brave Biomechanics, to observe volleyball players\' range and quality of motion. Using this athletic screening system aids in preventing injury and improving athletic performance. Our team created a Canvas course of tutorials on how to use Valor, and we reduced the general movement screening time.', 'Dr. Alicia Montalvo', 3, 'Coben Bourguet, Mohamed Almazrouei, Karla Diaz Aguilar', 'IEE 486', 'Yes', 'No', 'No', 'https://www.youtube.com/embed/_0cOnMozgiQ', 'https://youtu.be/_0cOnMozgiQ', '2024-04-16', 'YES'),
(131, 'cjperki5@asu.edu', 'Caleb Perkins', '23F-009 Los Alamos National Labs 2 - People Arrival Process', 'A recent change in scope at Los Alamos National Laboratories has resulted in an influx of people arriving throughout the day, causing the current entry process to be inefficient. The process must be reworked and streamlined to reduce the average time spent in the system. A virtual model of the ingress and egress processes was created using SIMIO simulation software.', 'Christopher Russell', 3, 'Caleb Perkins,  Aryzema Urrutia, Blakely Balzer', 'IEE 486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/3Qx7fofFC28', 'https://youtu.be/3Qx7fofFC28', '2024-04-16', 'YES'),
(132, 'ielaradi@asu.edu', 'Ibrahim Elaradi', '23F-023 Iquebal Project #2', 'Enhance waste sorting efficiency and increase recycling rates at SRP through advanced methods. Ensure regulatory compliance and foster sustainability awareness among employees. Ultimately, create a more efficient and environmentally conscious waste management system.', 'ASU - Ashif Iquebal', 4, 'Ibrahim Elaradi, Omer Almohammadi, Osamah Alqahtani, Abdullah Alrasheed', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/HJPJuWoTjT4?si=FcprUamVmEK_sp6V', 'https://youtu.be/HJPJuWoTjT4?si=FcprUamVmEK_sp6V', '2024-04-16', 'YES'),
(133, 'twsmit13@asu.edu', 'Trevor W. Smith', '23F-017 Collins Aerospace - Yield and SPC Tool Development', 'Our objective for our sponsor Collins Aerospace was to develop and deliver a discrete simulation model of an assembly line in the Collins Aerospace factory. The aim of the simulation is to do sensitivity analysis given process paramaters such as cycle time and first pass yield and how these inputs affect the total cost of quality and the operational costs as a whole.', 'Collins Aerospace', 3, 'Trevor W. Smith, Lauren Cooper, Logan Nipar', 'IEE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/A6MY7zs3yG8', 'https://youtu.be/A6MY7zs3yG8', '2024-04-16', 'YES'),
(134, 'rconcann@asu.edu', 'Ryan Concannon', '23F-015 Benchmark - Site Layout and Workflow', 'During our Capstone project, we applied Lean Six Sigma methodology and the DMAIC framework to enhance the operational efficiency and quality of an advanced electronics/computer manufacturing line. We conducted a thorough analysis using tools like value stream maps and spaghetti diagrams to identify inefficiencies and establish key performance indicators through quantitative and qualitative data collection. Our deliverables included comprehensive process improvement recommendations and updated visual documentation of the manufacturing flow, contributing to a strategic roadmap for continuous enhancement of the production line.', 'Javad Mahmoudzadeh', 3, 'Ryan Concannon, Jackson Weekley, Daniel Drotzmann', 'IEE486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/lziqYcVye54', 'https://youtu.be/lziqYcVye54', '2024-04-16', 'NO'),
(135, 'malhaje6@asu.edu', 'Mohamed Alhajeri', '23F-025 Iquebal Project #3', 'Directed Energy Deposition (DED) stands at the forefront of a manufacturing revolution, offering diverse industries a highly versatile additive manufacturing technology. DED\'s adaptability to various materials, reduced lead times, cost-effective, sustainable production make it a game changer in manufacturing. Our team will research the monitoring and control sensors used in DED and evaluate them to highlight and identify which sensors or components work best for the task at hand.', 'Ashif Iquebal', 1, 'Mohamed Alhajeri', 'IEE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/ZjGkf6N3MME', 'https://youtu.be/ZjGkf6N3MME', '2024-04-16', 'YES'),
(136, 'Mjbird1@asu.edu', 'Michael Bird', '23F-013 Iquebal Project #1 - Waste Generation Management', 'Our project focused on understanding and analyzing Salt River Projects’ current reel tracking processes. These reels hold electrical cables that SRP uses to power the greater phoenix valley and currently they have 2 years to use and return these steel reels to ensure they get a $2000 credit. Our group and the sponsor, Ashif Iquebal, determined why these reels werent being returned on time and how to improve efficiencies', 'Ashif Iquebal', 3, 'Michael Bird, Musaad Aldawsari, Faisal Alharbi', 'IEE 486', 'No', 'No', 'No', 'https://www.youtube.com/embed/7k1Lbmj5Fpo', 'https://www.youtube.com/watch?v=7k1Lbmj5Fpo', '2024-04-16', 'YES'),
(137, 'ktngo3@asu.edu', 'Katelyn Ngo', '23F-012 SCAI IT - Business Process Analysis', 'With SCAI growing, the Brickyard building space has become a major constraint. We created 3 databases that auto-populate assigned faculty and assigned students to the corresponding cubicle lab. We have also included utilization and funding ratio as well as visual color cues to help eliminate the time it takes Lincoln to pull the information he needs as well as make more informed decisions on how to reallocate and optimize the available space.', 'ASU SCAI IT, Lincoln Slade', 3, 'Katelyn Ngo, Santos Quintero, Anushak Sharma', 'IEE486', 'Yes', 'Yes', 'No', 'https://www.youtube.com/embed/cVeUGIH1rxE', 'https://youtu.be/cVeUGIH1rxE', '2024-04-16', 'YES'),
(138, 'aherna87@asu.edu', 'Antonio Hernandez Gonzalez', '23F-007 L3Harris - Plotting Area Analysis', 'The L3Harris production line for the potting process is being moved and updated with new machinery and tools. Currently, operators need to restock materials themselves and move any finished product along the line. L3Harris wants to cut down waste by introducing a water spider role which will supply materials, move finished goods, and remove any waste throughout the system.', 'L3HARRIS, David Little, Hugo Garcia', 3, 'Antonio Hernandez Gonzalez, Jacob Call, Gabriel Jimenez', 'IEE 486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/6mljH-ZmsLA', 'https://youtu.be/6mljH-ZmsLA', '2024-04-16', 'NO'),
(139, 'mwijenje@asu.edu', 'Max Wijenje', '23F-006 Innovation Space 2 - Steelcase: Learning Environment to Enhance STEM Education', 'This project addresses the pressing challenges in STEM(Science, Technology, Engineering, and Mathematics) education We are reimagining learning environments to actively engage students and accommodate evolving pedagogies', 'InnovationSpace', 2, 'Max Wijenje, Mohammed Almeshal', 'IEE 486', 'No', 'No', 'Yes', 'https://www.youtube.com/embed/5QKa2cD7s_E', 'https://youtu.be/5QKa2cD7s_E', '2024-04-16', 'NO'),
(140, 'ramusgra@asu.edu', 'Race Musgrave', 'SCAI CS/E-043 Fairmont Scottsdale Princess - Development of a State-of-the-Art Events & Property Map Hotel App for an Elevated Guest Experience', 'The overall goal of the project was to create an app to assist hotel guests in accessing information and navigating the hotel property. Ultimately the focus became hotel navigation through the mode of Apple’s indoor maps and an iOS app to display this map. This process involves taking the hotel\'s floor plans, converting them through an intensive process to a format called IMDF and then embedding the map file into the app.', 'Michael Ortiz (Sustainability Manager) michael.ortiz@fairmont.com', 5, 'Race Musgrave, Nicholas Toland, William Crabtree, Jesus Encinas, Devin Ath', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/vVnS9rGlmD0', 'https://youtu.be/vVnS9rGlmD0', '2024-04-18', 'YES'),
(141, 'lellswo2@asu.edu', 'Logan Ellsworth', 'SCAI CS/E-037 Digital Pantry', 'A mobile application to store ingredients, create lists and recipes, and generate new recipes with your ingredients. All with household sharing. Benefit from home cooking, reduced food waste, and better communication with everyone at the dinner table.', 'Katie Geraghty', 3, 'Austin Christiansen, Jackson Rhea, Logan Ellsworth', 'CSE486', 'No', 'No', 'No', 'https://www.youtube.com/embed/PRTwppYts-w?si=tfuk836H9Z_gSX4r', 'https://youtu.be/PRTwppYts-w?si=tfuk836H9Z_gSX4r', '2024-04-23', 'YES'),
(142, 'agandava@asu.edu', 'Abhisekhar Bharadwaj Gandavarapu', 'SCAI CS/E-091 NASA - Web-Based Game for Psyche 12N', 'Asteroid Tycoon is our NASA-sponsored web game that aims to deliver an immersive and educational experience, fostering excitement for space exploration and highlighting the NASA Psyche mission. Players engage in strategic resource extraction within an asteroid system, progressing through a tech tree, exploring caves, and deploying satellites to uncover hidden resources. Grounded in reality, this game offers a formal platform for understanding future space missions while promoting scientific curiosity and learning.', 'NASA', 4, 'Adrian Mena Altamirano, Abhisekhar Bharadwaj Gandavarapu, Justin Lavi, Joesph Dunagan', 'CSE486', 'Yes', 'Yes', 'Yes', 'https://www.youtube.com/embed/FL7AsPCRMEQ', 'https://www.youtube.com/watch?v=FL7AsPCRMEQ', '2024-04-25', 'NO');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `ShowcaseEntries`
--
ALTER TABLE `ShowcaseEntries`
  ADD PRIMARY KEY (`EntryID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `ShowcaseEntries`
--
ALTER TABLE `ShowcaseEntries`
  MODIFY `EntryID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=143;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
